// Ghidra decompiled output for: chromatron1
// Auto-generated by pyghidra

// Function: entry @ 0x000022c0

void entry(void)

{
  int in_stack_00000000;
  
                    /* WARNING: Subroutine does not return */
  FUN_000022f4(in_stack_00000000,&stack0x00000004,&stack0x00000004 + (in_stack_00000000 + 1) * 4);
}



// Function: FUN_000022f4 @ 0x000022f4

void FUN_000022f4(undefined8 param_1,undefined4 *param_2,int *param_3)

{
  char cVar1;
  char *pcVar2;
  int *piVar3;
  int iVar4;
  char *pcVar5;
  void *local_20 [8];
  
  FUN_000024bc();
  _NXArgc = (undefined4)param_1;
  _NXArgv = param_2;
  _environ = param_3;
  if (*(code **)PTR_00012cf8 != (code *)0x0) {
    (**(code **)PTR_00012cf8)();
  }
  if (*(code **)PTR_00012cf4 != (code *)0x0) {
    (**(code **)PTR_00012cf4)();
  }
  ___keymgr_dwarf2_register_sections();
  if (*(int *)PTR_FUN_00008014 != 0) {
    (*(code *)PTR_FUN_00008014)();
  }
  FUN_00002474();
  if (*(int *)PTR_SUB_00008010 != 0) {
    (*(code *)PTR_SUB_00008010)();
  }
  FUN_00002510("__dyld_mod_term_funcs",local_20);
  if (local_20[0] != (void *)0x0) {
    _atexit(local_20[0]);
  }
  *(undefined4 *)PTR_00012cf0 = 0;
  pcVar2 = (char *)*param_2;
  if (pcVar2 != (char *)0x0) {
    pcVar5 = (char *)0x0;
    iVar4 = 0;
    cVar1 = *pcVar2;
    while (cVar1 != '\0') {
      if (pcVar2[iVar4] == '/') {
        pcVar5 = pcVar2 + iVar4;
      }
      iVar4 = iVar4 + 1;
      pcVar2 = (char *)*param_2;
      cVar1 = pcVar2[iVar4];
    }
    if (pcVar5 == (char *)0x0) {
      ___progname = (undefined *)*param_2;
    }
    else {
      ___progname = pcVar5 + 1;
    }
  }
  iVar4 = *param_3;
  piVar3 = param_3;
  while (iVar4 != 0) {
    piVar3 = piVar3 + 1;
    iVar4 = *piVar3;
  }
  iVar4 = FUN_00002bc0(param_1,param_2,param_3,piVar3 + 1);
                    /* WARNING: Subroutine does not return */
  _exit(iVar4);
}



// Function: FUN_00002474 @ 0x00002474

void FUN_00002474(void)

{
  code *local_20 [8];
  
  FUN_00002510("__dyld_make_delayed_module_initializer_calls",local_20);
  (*local_20[0])();
  return;
}



// Function: FUN_000024bc @ 0x000024bc

void FUN_000024bc(void)

{
  if (DAT_00012d88 != 0) {
    return;
  }
  syscall();
  syscall();
  trapWord(0x1f,1,1);
  (*(code *)0x0)(0x3b,
                 "The kernel support for the dynamic linker is not present to run this program.\n",
                 0x4e);
  return;
}



// Function: FUN_00002510 @ 0x00002510

void FUN_00002510(void)

{
                    /* WARNING: Could not recover jumptable at 0x0000251c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*DAT_00012d8c)();
  return;
}



// Function: FUN_000025a4 @ 0x000025a4

void FUN_000025a4(int param_1,int param_2)

{
  int iStack00000018;
  int iStack0000001c;
  int local_20;
  int *local_1c;
  int *local_18;
  
  local_18 = (int *)0x0;
  iStack00000018 = param_1;
  iStack0000001c = param_2;
  local_20 = __keymgr_get_and_lock_processwide_ptr(0x12d);
  local_1c = &local_20;
  do {
    if (*local_1c == 0) {
LAB_00002664:
      __keymgr_set_and_unlock_processwide_ptr(0x12d,local_20);
      if (local_18 != (int *)0x0) {
        if (local_18[3] != 0) {
          (*(code *)local_18[3])(local_18);
        }
        _free(local_18);
      }
      return;
    }
    if ((*(int *)(*local_1c + 4) == iStack00000018) && (*(int *)(*local_1c + 8) == iStack0000001c))
    {
      local_18 = (int *)*local_1c;
      *local_1c = local_18[4];
      if (*local_18 != 0x28) {
                    /* WARNING: Subroutine does not return */
        _abort();
      }
      goto LAB_00002664;
    }
    local_1c = (int *)(*local_1c + 0x10);
  } while( true );
}



// Function: FUN_000026c0 @ 0x000026c0

void FUN_000026c0(void)

{
  __init_keymgr();
  if ((*(int *)(PTR_00012cfc + 8) == 0) || (*(ushort *)(*(int *)(PTR_00012cfc + 8) + 4) < 3)) {
    __dyld_register_func_for_add_image(PTR_LAB_0000801c);
    __dyld_register_func_for_remove_image(PTR_FUN_00008018);
  }
  return;
}



// Function: FUN_00002740 @ 0x00002740

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_00002740(void)

{
  undefined8 uVar1;
  undefined8 uVar2;
  undefined4 local_a0;
  undefined4 uStack_9c;
  char local_90 [4];
  undefined4 uStack_8c;
  undefined4 local_80;
  undefined4 uStack_7c;
  undefined4 uStack_78;
  undefined4 uStack_74;
  undefined4 uStack_70;
  undefined4 uStack_6c;
  undefined4 local_60;
  undefined4 uStack_5c;
  undefined4 local_50;
  undefined4 uStack_4c;
  undefined4 local_40;
  undefined4 uStack_3c;
  
  local_a0 = DAT_00007fb0;
  uStack_9c = _DAT_00007fb4;
  local_50 = DAT_00007fe0;
  uStack_4c = DAT_00007fe4;
  local_90 = (char  [4])s_Hwind_00007fb7._1_4_;
  uStack_8c = ram0x00007fbc;
  local_60 = DAT_00007fd8;
  uStack_5c = DAT_00007fdc;
  local_40 = DAT_00007fe8;
  uStack_3c = DAT_00007fec;
  local_80 = DAT_00007fc0;
  uStack_7c = DAT_00007fc4;
  uStack_78 = DAT_00007fc8;
  uStack_74 = DAT_00007fcc;
  uStack_70 = DAT_00007fd0;
  uStack_6c = DAT_00007fd4;
  uVar1 = _GetWindowEventTarget(DAT_00012da4);
  uVar2 = _NewEventHandlerUPP(PTR_FUN_00008038);
  _InstallEventHandler(uVar1,uVar2,1,&local_a0,0,0);
  uVar1 = _GetWindowEventTarget(DAT_00012da4);
  uVar2 = _NewEventHandlerUPP(PTR_FUN_00008034);
  _InstallEventHandler(uVar1,uVar2,1,local_90,0,0);
  uVar1 = _GetWindowEventTarget(DAT_00012da4);
  uVar2 = _NewEventHandlerUPP(PTR_FUN_00008030);
  _InstallEventHandler(uVar1,uVar2,3,&local_80,0,0);
  uVar1 = _GetWindowEventTarget(DAT_00012da4);
  uVar2 = _NewEventHandlerUPP(PTR_FUN_0000802c);
  _InstallEventHandler(uVar1,uVar2,1,&local_60,0,0);
  uVar1 = _GetWindowEventTarget(DAT_00012da4);
  uVar2 = _NewEventHandlerUPP(PTR_FUN_00008028);
  _InstallEventHandler(uVar1,uVar2,1,&local_50,0,0);
  uVar1 = _GetWindowEventTarget(DAT_00012da4);
  uVar2 = _NewEventHandlerUPP(PTR_FUN_00008024);
  _InstallEventHandler(uVar1,uVar2,1,&local_40,0,0);
  return;
}



// Function: FUN_00002924 @ 0x00002924

void FUN_00002924(void)

{
  undefined8 uVar1;
  int local_20 [8];
  
  local_20[0] = 0;
  uVar1 = ___CFStringMakeConstantString("menus");
  _CreateNibReference(uVar1,local_20);
  if (local_20[0] != 0) {
    uVar1 = ___CFStringMakeConstantString("MenuBar");
    _SetMenuBarFromNib(local_20[0],uVar1);
    _DisposeNibReference(local_20[0]);
  }
  return;
}



// Function: FUN_00002998 @ 0x00002998

void FUN_00002998(void)

{
  undefined2 uVar1;
  undefined8 uVar2;
  char local_20 [32];
  
  uVar2 = ___CFStringMakeConstantString("UseMouseWheelToChangeLevel");
  DAT_00008020 = _CFPreferencesGetAppBooleanValue(uVar2,*(undefined4 *)PTR_00012d0c,local_20);
  if (local_20[0] == '\0') {
    DAT_00008020 = 1;
  }
  _GetMenuCommandMark(0,0x57686565,&DAT_00012dac);
  uVar1 = 0;
  if (DAT_00008020 != 0) {
    uVar1 = DAT_00012dac;
  }
  _SetMenuCommandMark(0,0x57686565,uVar1);
  return;
}



// Function: FUN_00002a4c @ 0x00002a4c

void FUN_00002a4c(void)

{
  undefined4 uVar1;
  undefined2 uVar3;
  undefined8 uVar4;
  undefined4 *puVar2;
  
  puVar2 = (undefined4 *)PTR_00012d04;
  if (DAT_00008020 != 0) {
    puVar2 = (undefined4 *)PTR_00012d08;
  }
  uVar1 = *puVar2;
  uVar4 = ___CFStringMakeConstantString("UseMouseWheelToChangeLevel");
  _CFPreferencesSetAppValue(uVar4,uVar1,*(undefined4 *)PTR_00012d0c);
  uVar3 = 0;
  if (DAT_00008020 != 0) {
    uVar3 = DAT_00012dac;
  }
  _SetMenuCommandMark(0,0x57686565,uVar3);
  return;
}



// Function: FUN_00002aec @ 0x00002aec

void FUN_00002aec(void)

{
  undefined8 uVar1;
  undefined4 local_20;
  undefined4 uStack_1c;
  
  local_20 = DAT_00007ff0;
  uStack_1c = DAT_00007ff4;
  _CreateNewWindow(6,0x2000009,&local_20,&DAT_00012da4);
  uVar1 = ___CFStringMakeConstantString("Chromatron 1 (v1.15)");
  _SetWindowTitleWithCFString(DAT_00012da4,uVar1);
  return;
}



// Function: FUN_00002b64 @ 0x00002b64

int FUN_00002b64(void)

{
  int iVar1;
  undefined1 auStack_460 [80];
  char acStack_410 [1040];
  
  iVar1 = _FSFindFolder(0xffffffffffff8005,0x70726566,1,auStack_460);
  if (iVar1 == 0) {
    iVar1 = _FSRefMakePath(auStack_460,acStack_410,0x400);
  }
  if (iVar1 == 0) {
    iVar1 = _chdir(acStack_410);
  }
  return iVar1;
}



// Function: FUN_00002bc0 @ 0x00002bc0

undefined8 FUN_00002bc0(void)

{
  FUN_00002b64();
  FUN_00005f38();
  FUN_00002924();
  FUN_00002998();
  FUN_00002aec();
  FUN_00002740();
  _RepositionWindow(DAT_00012da4,0,1);
  _ShowWindow(DAT_00012da4);
  _RunApplicationEventLoop();
  FUN_000068c0();
  _CFPreferencesAppSynchronize(*(undefined4 *)PTR_00012d0c);
  return 0;
}



// Function: FUN_00002c40 @ 0x00002c40

void FUN_00002c40(short param_1,short param_2,short param_3,short param_4)

{
  short local_20;
  short local_1e;
  short local_1c;
  short local_1a;
  
  local_1c = param_2 + param_4;
  local_1a = param_1 + param_3;
  local_20 = param_2;
  local_1e = param_1;
  _InvalWindowRect(DAT_00012da4,&local_20);
  return;
}



// Function: FUN_00002c9c @ 0x00002c9c

undefined8 FUN_00002c9c(undefined8 param_1,undefined8 param_2)

{
  undefined8 uVar1;
  undefined1 auStack_20 [4];
  uint local_1c;
  
  _GetEventParameter(param_2,0x2d2d2d2d,0x68636d64,0,0xe,0,auStack_20);
  if (local_1c == 0x57686565) {
    DAT_00008020 = (uint)(DAT_00008020 == 0);
    FUN_00002a4c();
    return 0;
  }
  if (local_1c < 0x57686566) {
    if (local_1c == 0x4e657874) {
      uVar1 = 0x3d;
    }
    else {
      if (local_1c != 0x50726576) {
        return 0xffffffffffffd96e;
      }
      uVar1 = 0x2d;
    }
  }
  else {
    if (local_1c == 0x70617374) {
      FUN_00002f78();
      return 0;
    }
    if (local_1c < 0x70617375) {
      if (local_1c == 0x636f7079) {
        FUN_00002ef8();
        return 0;
      }
      return 0xffffffffffffd96e;
    }
    if (local_1c != 0x72767274) {
      return 0xffffffffffffd96e;
    }
    uVar1 = 0x72;
  }
  FUN_00005e64(uVar1);
  return 0;
}



// Function: FUN_00002dc8 @ 0x00002dc8

undefined8 FUN_00002dc8(void)

{
  _QuitApplicationEventLoop();
  return 0;
}



// Function: FUN_00002dec @ 0x00002dec

undefined8 FUN_00002dec(void)

{
  undefined8 uVar1;
  undefined4 local_20 [8];
  
  uVar1 = _GetWindowPort(DAT_00012da4);
  local_20[0] = 0;
  FUN_000066e0();
  _QDBeginCGContext(uVar1,local_20);
  _CGContextFlush(local_20[0]);
  _QDEndCGContext(uVar1,local_20);
  return 0;
}



// Function: FUN_00002e58 @ 0x00002e58

undefined8 FUN_00002e58(undefined8 param_1,undefined8 param_2)

{
  int iVar1;
  undefined1 local_20 [4];
  uint local_1c [7];
  
  _GetEventParameter(param_2,0x6b636872,0x54455854,0,1,0,local_20);
  _GetEventParameter(param_2,0x6b6d6f64,0x6d61676e,0,4,0,local_1c);
  if (((local_1c[0] & 0x100) == 0) && (iVar1 = FUN_00005e64(local_20[0]), iVar1 != 0)) {
    return 0;
  }
  return 0xffffffffffffd96e;
}



// Function: FUN_00002ef8 @ 0x00002ef8

void FUN_00002ef8(void)

{
  char *pcVar1;
  int iVar2;
  size_t sVar3;
  undefined4 local_20 [8];
  
  local_20[0] = 0;
  pcVar1 = (char *)FUN_00005914();
  if ((pcVar1 != (char *)0x0) && (*pcVar1 != '\0')) {
    _ClearCurrentScrap();
    iVar2 = _GetCurrentScrap(local_20);
    if (iVar2 == 0) {
      sVar3 = _strlen(pcVar1);
      _PutScrapFlavor(local_20[0],0x54455854,0,sVar3,pcVar1);
    }
  }
  return;
}



// Function: FUN_00002f78 @ 0x00002f78

void FUN_00002f78(void)

{
  bool bVar1;
  longlong lVar2;
  void *pvVar3;
  int iVar4;
  undefined4 local_20;
  int local_1c [7];
  
  pvVar3 = (void *)0x0;
  local_1c[0] = 0;
  local_20 = 0;
  lVar2 = _GetCurrentScrap(&local_20);
  if (lVar2 == 0) {
    lVar2 = _GetScrapFlavorSize(local_20,0x54455854,local_1c);
  }
  iVar4 = (int)lVar2;
  bVar1 = true;
  if (iVar4 == 0) {
    pvVar3 = _calloc(local_1c[0] + 1,1);
    bVar1 = pvVar3 == (void *)0x0;
    if (!bVar1) {
      iVar4 = _GetScrapFlavorData(local_20,0x54455854,local_1c,pvVar3);
    }
  }
  if ((iVar4 == 0) && (!bVar1)) {
    FUN_00005ad4(pvVar3);
  }
  _free(pvVar3);
  return;
}



// Function: FUN_00003044 @ 0x00003044

undefined8 FUN_00003044(undefined8 param_1,undefined8 param_2)

{
  undefined8 uVar1;
  int local_20 [8];
  
  uVar1 = 0xffffffffffffd96e;
  if (DAT_00008020 != 0) {
    _GetEventParameter(param_2,0x6d77646c,0x6c6f6e67,0,4,0,local_20);
    uVar1 = 0x3d;
    if (0 < local_20[0]) {
      uVar1 = 0x2d;
    }
    FUN_00005e64(uVar1);
    uVar1 = 0;
  }
  return uVar1;
}



// Function: FUN_000030cc @ 0x000030cc

void FUN_000030cc(uint param_1,uint param_2,undefined8 param_3,undefined8 param_4,undefined8 param_5
                 ,longlong param_6)

{
  undefined8 uVar1;
  undefined8 uVar2;
  undefined8 uVar3;
  double dVar4;
  double dVar5;
  double dVar6;
  double dVar7;
  undefined4 local_38 [14];
  
  uVar1 = _GetWindowPort(DAT_00012da4);
  local_38[0] = 0;
  uVar2 = _CGDataProviderCreateWithData
                    (0,param_3,(longlong)(int)(uint)param_5 * (longlong)(int)param_6 * 3,0);
  uVar3 = _CGColorSpaceCreateDeviceRGB();
  uVar3 = _CGImageCreate(param_4,param_5,8,0x18,param_6 * 3,uVar3,0,uVar2);
  dVar4 = (double)CONCAT44(0x43300000,param_1 ^ 0x80000000) - DOUBLE_00007ff8;
  dVar7 = (double)CONCAT44(0x43300000,(uint)param_5 ^ 0x80000000) - DOUBLE_00007ff8;
  dVar5 = (double)CONCAT44(0x43300000,param_2 ^ 0x80000000) - DOUBLE_00007ff8;
  dVar6 = (double)CONCAT44(0x43300000,(uint)param_4 ^ 0x80000000) - DOUBLE_00007ff8;
  _QDBeginCGContext(uVar1,local_38);
  _CGContextDrawImage(local_38[0],(float)dVar4,(float)dVar5,(float)dVar6,(float)dVar7,uVar3);
  _QDEndCGContext(uVar1,local_38);
  _CGImageRelease(uVar3);
  _CGDataProviderRelease(uVar2);
  return;
}



// Function: FUN_00003228 @ 0x00003228

void FUN_00003228(undefined8 param_1,undefined2 param_2,undefined2 param_3,undefined2 param_4,
                 undefined2 param_5)

{
  undefined8 uVar1;
  undefined8 uVar2;
  undefined2 local_40;
  undefined2 local_3e;
  undefined2 local_3c;
  undefined2 local_3a;
  undefined4 local_30 [12];
  
  uVar1 = _GetWindowPort(DAT_00012da4);
  local_30[0] = 0;
  uVar2 = _CFStringCreateWithCString(*(undefined4 *)PTR_00012d00,param_1,0x600);
  local_40 = param_3;
  local_3e = param_2;
  local_3c = param_5;
  local_3a = param_4;
  _QDBeginCGContext(uVar1,local_30);
  _DrawThemeTextBox(uVar2,0,1,1,&local_40,0,local_30[0]);
  _QDEndCGContext(uVar1,local_30);
  _CFRelease(uVar2);
  return;
}



// Function: FUN_000032ec @ 0x000032ec

undefined8 FUN_000032ec(undefined8 param_1,undefined8 param_2)

{
  uint uVar2;
  undefined8 uVar1;
  int iVar3;
  undefined8 uVar4;
  short local_30;
  short local_2e;
  short local_20 [2];
  uint local_1c;
  undefined4 local_18;
  
  uVar2 = _GetEventKind(param_2);
  uVar2 = uVar2 & 0xffff;
  _GetEventParameter(param_2,0x6d62746e,0x6d62746e,0,2,0,local_20);
  if (local_20[0] == 1) {
    _GetEventParameter(param_2,0x6b6d6f64,0x6d61676e,0,4,0,&local_1c);
    if (uVar2 == 1) {
      DAT_00012da8 = -(local_1c & 0x1a00) >> 0x1f;
    }
    if (DAT_00012da8 != 0) {
      local_20[0] = 2;
    }
  }
  if (uVar2 == 2) {
    uVar4 = 6;
    if (local_20[0] != 2) {
      uVar4 = 4;
    }
LAB_0000340c:
    _GetEventParameter(param_2,0x6d6c6f63,0x51447074,0,4,0,&local_18);
    _GetWindowBounds(DAT_00012da4,0x21,&local_30);
    iVar3 = _PtInRect(local_18,&local_30);
    uVar1 = 0xffffffffffffd96e;
    if (iVar3 != 0) {
      iVar3 = _IsWindowHilited(DAT_00012da4);
      uVar1 = 0xffffffffffffd96e;
      if (iVar3 != 0) {
        FUN_000050d4(uVar4,(longlong)local_18._2_2_ - (longlong)local_2e,
                     (longlong)local_18._0_2_ - (longlong)local_30,0,0);
        uVar1 = 0;
      }
    }
  }
  else {
    if (uVar2 < 3) {
      if (uVar2 == 1) {
        uVar4 = 3;
        if (local_20[0] != 2) {
          uVar4 = 1;
        }
        goto LAB_0000340c;
      }
    }
    else if (uVar2 - 5 < 2) {
      uVar4 = 0;
      goto LAB_0000340c;
    }
    uVar1 = 0xffffffffffffd96e;
  }
  return uVar1;
}



// Function: FUN_000034b8 @ 0x000034b8

void FUN_000034b8(void)

{
  DAT_00008040 = 1;
  FUN_00002c40();
  return;
}



// Function: FUN_000034d8 @ 0x000034d8

bool FUN_000034d8(longlong param_1)

{
  return param_1 - 3U < 7;
}



// Function: FUN_000034ec @ 0x000034ec

void FUN_000034ec(undefined1 param_1,undefined1 param_2,undefined1 param_3,undefined1 param_4,
                 undefined4 param_5)

{
  int iVar1;
  int iVar2;
  undefined *puVar3;
  
  puVar3 = PTR_DAT_00012d70;
  iVar1 = *(int *)PTR_DAT_00012d74;
  if (iVar1 != 0x20) {
    iVar2 = iVar1 * 8;
    *(int *)PTR_DAT_00012d74 = iVar1 + 1;
    *(undefined1 *)(iVar2 + *(int *)puVar3) = param_1;
    *(undefined1 *)(iVar2 + *(int *)puVar3 + 1) = param_2;
    *(undefined1 *)(iVar2 + *(int *)puVar3 + 2) = param_3;
    *(undefined1 *)(iVar2 + *(int *)puVar3 + 3) = param_4;
    *(undefined4 *)(iVar2 + *(int *)puVar3 + 4) = param_5;
  }
  return;
}



// Function: FUN_00003568 @ 0x00003568

void FUN_00003568(uint param_1,int param_2,uint param_3,ulonglong param_4,undefined8 param_5)

{
  bool bVar1;
  undefined1 uVar2;
  uint uVar3;
  int iVar4;
  uint uVar5;
  undefined8 uVar6;
  uint uVar7;
  ulonglong uVar8;
  uint uVar9;
  
  iVar4 = param_2 * 300 + param_1 * 0x14;
  uVar2 = PTR_DAT_00012d6c[iVar4];
  uVar9 = (uint)(byte)PTR_DAT_00012d6c[iVar4 + 2];
  uVar7 = param_3 - uVar9;
  uVar3 = uVar7 & 7;
  PTR_DAT_00012d6c[param_3 + iVar4 + 4] = PTR_DAT_00012d6c[param_3 + iVar4 + 4] | (byte)param_4;
  uVar8 = param_4;
  switch(uVar2) {
  case 0:
  case 10:
    goto switchD_000035e8_caseD_0;
  case 1:
  case 2:
    return;
  case 3:
    if (uVar3 == 2) {
LAB_00003678:
      uVar9 = uVar9 + 6;
    }
    else if (uVar3 < 3) {
      bVar1 = uVar3 == 1;
LAB_00003650:
      if (!bVar1) {
        return;
      }
      uVar9 = uVar9 + 7;
    }
    else {
      if (uVar3 != 3) {
        return;
      }
LAB_00003670:
      uVar9 = uVar9 + 5;
    }
    goto LAB_00003684;
  case 4:
    if (uVar3 == 1) goto LAB_00003678;
    if (uVar3 < 2) {
      bVar1 = (uVar7 & 7) == 0;
      goto LAB_00003650;
    }
    if (uVar3 == 2) goto LAB_00003670;
    uVar9 = uVar9 + 4;
    if (uVar3 != 3) {
      return;
    }
LAB_00003684:
    param_3 = uVar9 & 7;
    goto switchD_000035e8_caseD_0;
  case 5:
    uVar8 = param_4 & (byte)PTR_DAT_00012d6c[param_2 * 300 + param_1 * 0x14 + 1];
    if ((uVar3 != 2) && (uVar3 != 6)) {
      return;
    }
    if ((int)uVar8 == 0) {
      return;
    }
    break;
  case 6:
    if ((param_4 & 4) != 0) {
      if (uVar3 == 2) {
        uVar5 = uVar9 + 2;
      }
      else if (uVar3 < 3) {
        if (uVar3 != 1) goto LAB_000036f4;
        uVar5 = uVar9 + 1;
      }
      else if (uVar3 == 5) {
        uVar5 = uVar9 + 5;
      }
      else {
        if (uVar3 != 6) goto LAB_000036f4;
        uVar5 = uVar9 + 6;
      }
      FUN_000034ec(param_1,param_2,uVar5 & 7,4,param_5);
    }
LAB_000036f4:
    if ((param_4 & 2) != 0) {
      if (uVar3 == 2) {
        uVar5 = uVar9 + 3;
      }
      else if (uVar3 < 3) {
        if ((uVar7 & 7) != 0) goto LAB_0000375c;
        uVar5 = uVar9 + 1;
      }
      else if (uVar3 == 5) {
        uVar5 = uVar9 + 4;
      }
      else {
        if (uVar3 != 7) goto LAB_0000375c;
        uVar5 = uVar9 + 6;
      }
      FUN_000034ec(param_1,param_2,uVar5 & 7,2,param_5);
    }
LAB_0000375c:
    if ((param_4 & 1) == 0) {
      return;
    }
    if (uVar3 == 2) {
      param_3 = uVar9 + 4;
    }
    else if (uVar3 < 3) {
      if ((uVar7 & 7) != 0) {
        return;
      }
      param_3 = uVar9 + 6;
    }
    else if (uVar3 == 5) {
      param_3 = uVar9 + 3;
    }
    else {
      if (uVar3 != 7) {
        return;
      }
      param_3 = uVar9 + 1;
    }
    param_3 = param_3 & 7;
    uVar8 = 1;
    break;
  case 7:
    if (uVar3 == 2) {
      uVar8 = 0;
      if ((param_4 & 4) != 0) {
        uVar8 = 2;
      }
      if ((param_4 & 2) != 0) {
        uVar8 = uVar8 | 1;
      }
      if ((param_4 & 1) != 0) {
        uVar8 = uVar8 | 4;
      }
    }
    else {
      if (uVar3 != 6) {
        return;
      }
      uVar8 = 1 - (ulonglong)(((uint)(byte)(((param_4 & 4) == 0) << 1) << 0x1c) >> 0x1d);
      if (((uint)param_4 >> 1 & 1) != 0) {
        uVar8 = uVar8 | 4;
      }
      if ((param_4 & 1) != 0) {
        uVar8 = uVar8 | 2;
      }
    }
    if ((int)param_5 != 0) {
      uVar8 = param_4;
    }
    break;
  case 8:
    if ((uVar7 & 7) == 0) {
      return;
    }
    if (uVar3 == 4) {
      return;
    }
    if ((uVar3 == 2) || (uVar6 = 0, uVar3 == 6)) {
      uVar6 = param_5;
    }
    FUN_000034ec(param_1,param_2,param_3,param_4,uVar6);
    uVar7 = uVar7 & 7;
    if (uVar7 == 3) {
      uVar9 = uVar9 + 5;
    }
    else if (uVar7 < 4) {
      if (uVar7 != 1) {
        return;
      }
      uVar9 = uVar9 + 7;
    }
    else if (uVar7 == 5) {
      uVar9 = uVar9 + 3;
    }
    else {
      if (uVar7 != 7) {
        return;
      }
      uVar9 = uVar9 + 1;
    }
    param_3 = uVar9 & 7;
    param_5 = 0;
    break;
  case 9:
    if (uVar3 == 2) {
      uVar8 = 1;
      do {
        if ((uVar8 & param_4) != 0) {
          FUN_000034ec(param_1,param_2,uVar9 & 7,uVar8,DAT_00012dc8);
          FUN_000034ec(param_1,param_2,uVar9 + 4 & 7,uVar8,DAT_00012dc8);
          DAT_00012dc8 = DAT_00012dc8 + 1;
        }
        uVar8 = (uVar8 & 0x7fffffff) << 1;
      } while ((int)uVar8 < 5);
      return;
    }
    return;
  case 0xb:
    if (((uVar7 & 7) != 0) && (uVar3 != 4)) {
      return;
    }
switchD_000035e8_caseD_0:
    break;
  case 0xc:
    do {
      param_1 = param_1 + *(int *)(&DAT_00008044 + param_3 * 4);
      param_2 = param_2 + *(int *)(&DAT_00008064 + param_3 * 4);
      if (0xe < param_1) {
        return;
      }
      if (param_2 < 0) {
        return;
      }
      if (0xe < param_2) {
        return;
      }
    } while (PTR_DAT_00012d6c[param_2 * 300 + param_1 * 0x14] != '\f');
    FUN_000034ec(param_1,param_2,param_3,param_4,param_5);
    return;
  default:
                    /* WARNING: Subroutine does not return */
    FUN_00006ac0("%s:%u: failed assertion `%s\'\n","../game.c",0x1a6,"0");
  }
  FUN_000034ec(param_1,param_2,param_3,uVar8,param_5);
  return;
}



// Function: FUN_00003a58 @ 0x00003a58

void FUN_00003a58(void)

{
  char cVar1;
  char cVar2;
  byte bVar3;
  undefined4 uVar4;
  undefined *puVar5;
  undefined *puVar6;
  undefined *puVar7;
  undefined *puVar8;
  undefined *puVar9;
  int iVar10;
  int iVar11;
  uint uVar12;
  int iVar13;
  int iVar14;
  int iVar15;
  longlong lVar16;
  
  *(undefined **)PTR_DAT_00012d68 = PTR_DAT_00012d64;
  puVar5 = PTR_DAT_00012d74;
  *(undefined **)PTR_DAT_00012d70 = PTR_DAT_00012d60;
  DAT_00012dc8 = 1;
  *(undefined4 *)puVar5 = 0;
  FUN_000034ec();
  if (*(int *)puVar5 != 0) {
    lVar16 = 0x3ff;
    do {
      puVar8 = PTR_DAT_00012d74;
      puVar6 = PTR_DAT_00012d70;
      puVar5 = PTR_DAT_00012d5c;
      iVar15 = 0;
      iVar14 = *(int *)PTR_DAT_00012d74;
      uVar4 = *(undefined4 *)PTR_DAT_00012d68;
      *(undefined4 *)PTR_DAT_00012d68 = *(undefined4 *)PTR_DAT_00012d70;
      *(undefined4 *)puVar6 = uVar4;
      *(undefined4 *)puVar8 = 0;
      *(int *)puVar5 = iVar14;
      if (0 < iVar14) {
        do {
          puVar5 = PTR_DAT_00012d68;
          iVar11 = iVar15 * 8;
          iVar10 = iVar11 + *(int *)PTR_DAT_00012d68;
          iVar14 = (uint)*(byte *)(iVar10 + 2) +
                   (uint)*(byte *)(iVar10 + 1) * 300 +
                   (uint)*(byte *)(iVar11 + *(int *)PTR_DAT_00012d68) * 0x14;
          PTR_DAT_00012d6c[iVar14 + 0xc] = PTR_DAT_00012d6c[iVar14 + 0xc] | *(byte *)(iVar10 + 3);
          iVar14 = *(int *)puVar5;
          *(char *)(iVar11 + iVar14) =
               *(char *)(iVar11 + iVar14) +
               (&DAT_00008047)[(uint)*(byte *)(iVar11 + iVar14 + 2) * 4];
          iVar14 = iVar11 + *(int *)puVar5;
          *(char *)(iVar14 + 1) =
               *(char *)(iVar14 + 1) + (&DAT_00008067)[(uint)*(byte *)(iVar14 + 2) * 4];
          bVar3 = *(byte *)(iVar11 + *(int *)puVar5);
          iVar11 = iVar11 + *(int *)puVar5;
          if ((bVar3 < 0xf) && (*(byte *)(iVar11 + 1) < 0xf)) {
            FUN_00003568(bVar3,*(byte *)(iVar11 + 1),*(undefined1 *)(iVar11 + 2),
                         *(undefined1 *)(iVar11 + 3),*(undefined4 *)(iVar11 + 4));
          }
          iVar15 = iVar15 + 1;
        } while (iVar15 < *(int *)PTR_DAT_00012d5c);
      }
      puVar8 = PTR_DAT_00012d74;
      puVar6 = PTR_DAT_00012d70;
      puVar5 = PTR_DAT_00012d6c;
      iVar14 = 0;
      if (0 < *(int *)PTR_DAT_00012d74) {
        do {
          puVar9 = PTR_DAT_00012d74;
          puVar7 = PTR_DAT_00012d70;
          iVar11 = iVar14 * 8;
          uVar12 = (uint)*(byte *)(iVar11 + *(int *)puVar6);
          iVar15 = iVar11 + *(int *)puVar6;
          if ((((uVar12 < 0xf) && (*(byte *)(iVar15 + 1) < 0xf)) && (*(int *)(iVar15 + 4) != 0)) &&
             (iVar10 = (uint)*(byte *)(iVar15 + 1) * 300 + uVar12 * 0x14, puVar5[iVar10] == '\a')) {
            iVar13 = 0;
            cVar1 = puVar5[iVar10 + 2];
            cVar2 = *(char *)(iVar15 + 2);
            if (0 < *(int *)puVar8) {
              do {
                iVar15 = iVar13 * 8 + *(int *)puVar7;
                if (*(int *)(iVar15 + 4) == *(int *)(iVar11 + *(int *)puVar7 + 4)) {
                  if ((iVar14 == iVar13) == ((cVar2 - cVar1 & 7U) == 2)) {
                    iVar10 = (uint)*(byte *)(iVar15 + 3) * 4 + 0x8098;
                  }
                  else {
                    iVar10 = (uint)*(byte *)(iVar15 + 3) * 4 + 0x8084;
                  }
                  *(undefined1 *)(iVar15 + 3) = *(undefined1 *)(iVar10 + 3);
                }
                iVar13 = iVar13 + 1;
              } while (iVar13 < *(int *)puVar9);
            }
          }
          iVar14 = iVar14 + 1;
        } while (iVar14 < *(int *)puVar8);
      }
    } while ((*(int *)PTR_DAT_00012d74 != 0) && (lVar16 = lVar16 + -1, lVar16 != 0));
  }
  return;
}



// Function: FUN_00003d60 @ 0x00003d60

void FUN_00003d60(void)

{
  undefined *puVar1;
  int iVar2;
  int iVar3;
  undefined *puVar4;
  int iVar5;
  int iVar6;
  longlong lVar7;
  
  puVar1 = PTR_DAT_00012d6c;
  iVar2 = 0;
  iVar3 = 0;
  do {
    iVar5 = 0;
    puVar4 = puVar1 + iVar3;
    do {
      lVar7 = 8;
      iVar6 = 0;
      do {
        puVar4[iVar6 + 0xc] = 0;
        puVar4[iVar6 + 4] = 0;
        lVar7 = lVar7 + -1;
        iVar6 = iVar6 + 1;
      } while (lVar7 != 0);
      iVar5 = iVar5 + 1;
      puVar4 = puVar4 + 0x14;
    } while (iVar5 < 0xf);
    iVar2 = iVar2 + 1;
    iVar3 = iVar3 + 300;
  } while (iVar2 < 0xf);
  return;
}



// Function: FUN_00003dd4 @ 0x00003dd4

void FUN_00003dd4(void)

{
  undefined *puVar1;
  undefined1 *puVar2;
  undefined *puVar3;
  longlong lVar4;
  
  puVar1 = PTR_DAT_00012d6c + 0x1068;
  puVar3 = PTR_DAT_00012d6c;
  do {
    puVar2 = puVar3 + 3;
    lVar4 = 0xf;
    do {
      *puVar2 = 0;
      puVar2 = puVar2 + 0x14;
      lVar4 = lVar4 + -1;
    } while (lVar4 != 0);
    puVar3 = puVar3 + 300;
  } while ((int)puVar3 <= (int)puVar1);
  return;
}



// Function: FUN_00003e1c @ 0x00003e1c

void FUN_00003e1c(void)

{
  int iVar1;
  longlong lVar2;
  longlong lVar3;
  int iVar4;
  
  lVar2 = 0;
  iVar1 = 0;
  do {
    lVar3 = 0;
    iVar4 = iVar1;
    do {
      if (PTR_DAT_00012d6c[iVar4] == '\x02') {
        FUN_00003a58(lVar3,lVar2,PTR_DAT_00012d6c[iVar4 + 2],PTR_DAT_00012d6c[iVar4 + 1]);
      }
      lVar3 = lVar3 + 1;
      iVar4 = iVar4 + 0x14;
    } while ((int)lVar3 < 0xf);
    lVar2 = lVar2 + 1;
    iVar1 = iVar1 + 300;
  } while ((int)lVar2 < 0xf);
  return;
}



// Function: FUN_00003ea4 @ 0x00003ea4

void FUN_00003ea4(void)

{
  FUN_00003d60();
  FUN_00003e1c();
  return;
}



// Function: FUN_00003ecc @ 0x00003ecc

bool FUN_00003ecc(int param_1)

{
  byte bVar1;
  byte *pbVar2;
  byte bVar3;
  longlong lVar4;
  
  bVar3 = 0;
  lVar4 = 8;
  pbVar2 = (byte *)(param_1 + 4);
  do {
    bVar1 = *pbVar2;
    pbVar2 = pbVar2 + 1;
    bVar3 = bVar3 | bVar1;
    lVar4 = lVar4 + -1;
  } while (lVar4 != 0);
  return *(byte *)(param_1 + 1) == bVar3;
}



// Function: FUN_00003f00 @ 0x00003f00

ulonglong FUN_00003f00(uint param_1)

{
  ulonglong uVar1;
  
  if (0x7f < param_1) {
                    /* WARNING: Subroutine does not return */
    FUN_00006ac0("%s:%u: failed assertion `%s\'\n","../game.c",0x2cc,"n >= 0 && n < 128");
  }
  if ((int)param_1 < 0x20) {
    uVar1 = (ulonglong)(byte)(&DAT_000080ac)[param_1];
  }
  else if ((int)param_1 < 0x40) {
    uVar1 = (ulonglong)(byte)(&DAT_000080ac)[param_1 + 0xd & 0x1f] + 0x60;
  }
  else if ((int)param_1 < 0x60) {
    uVar1 = (ulonglong)(byte)(&DAT_000080ac)[param_1 + 0x14 & 0x1f] + 0x20;
  }
  else {
    uVar1 = (ulonglong)(byte)(&DAT_000080ac)[param_1 + 5 & 0x1f] + 0x40;
  }
  return uVar1;
}



// Function: FUN_00003fc8 @ 0x00003fc8

longlong FUN_00003fc8(uint param_1,ulonglong param_2)

{
  longlong lVar1;
  
  lVar1 = FUN_00003f00(((ulonglong)param_1 & 0x1f) + (param_2 & 0x7ffffff) * 0x20);
  return lVar1 + ((ulonglong)(uint)((int)param_1 >> 5) & 0x1ffffff) * 0x80;
}



// Function: FUN_0000400c @ 0x0000400c

longlong FUN_0000400c(ulonglong param_1)

{
  int iVar1;
  longlong lVar2;
  int iVar3;
  
  param_1 = (param_1 & 0x1fffffff) * 8 + param_1;
  lVar2 = param_1 + (param_1 & 0xffffff) * 0x100;
  lVar2 = lVar2 + ((int)lVar2 >> 4);
  iVar3 = (int)lVar2;
  iVar1 = iVar3 >> 0x1f;
  return lVar2 + ((longlong)(iVar3 / 0xf + iVar1) - (longlong)iVar1) * -0xf + 1;
}



// Function: FUN_00004050 @ 0x00004050

void FUN_00004050(void)

{
  undefined *puVar1;
  undefined *puVar2;
  int *piVar3;
  longlong lVar4;
  int iVar5;
  int iVar6;
  
  FUN_000034b8(0,0,0x280,0x1e0);
  puVar2 = PTR_DAT_00012d58;
  puVar1 = PTR_DAT_00012d54;
  lVar4 = 0x3f;
  piVar3 = (int *)(PTR_DAT_00012d58 + 0xfc);
  do {
    iVar5 = *piVar3;
    piVar3 = piVar3 + -1;
    if (iVar5 != 0) break;
    lVar4 = lVar4 + -1;
  } while (-1 < lVar4);
  iVar5 = (int)lVar4;
  iVar6 = 1;
  if (8 < iVar5) {
    iVar6 = 2;
  }
  if (0x12 < iVar5) {
    iVar6 = iVar6 + 1;
  }
  if (0x19 < iVar5) {
    iVar6 = iVar6 + 1;
  }
  if (0x22 < iVar5) {
    iVar6 = iVar6 + 2;
  }
  iVar5 = 0;
  lVar4 = 0x40;
  do {
    if (*(int *)(puVar2 + iVar5) == 0) {
      if (0 < iVar6) {
        *(undefined4 *)(puVar1 + iVar5) = 1;
        iVar6 = iVar6 + -1;
      }
    }
    else {
      *(undefined4 *)(puVar1 + iVar5) = 1;
    }
    iVar5 = iVar5 + 4;
    lVar4 = lVar4 + -1;
  } while (lVar4 != 0);
  return;
}



// Function: FUN_00004138 @ 0x00004138

void FUN_00004138(void)

{
  undefined *puVar1;
  byte bVar2;
  FILE *pFVar3;
  size_t sVar4;
  uint uVar5;
  uint uVar6;
  void *pvVar7;
  uint uVar8;
  longlong lVar9;
  int iVar10;
  byte abStack_50 [32];
  byte local_30 [48];
  
  pFVar3 = _fopen("com.silverspaceship.chromatron.dat","rb");
  if ((pFVar3 == (FILE *)0x0) || (sVar4 = _fread(abStack_50,0x20,1,pFVar3), sVar4 != 1)) {
    pvVar7 = _memset(PTR_DAT_00012d58,0,0x100);
  }
  else {
    iVar10 = 0;
    do {
      uVar8 = 0;
      uVar5 = FUN_0000400c(iVar10);
      lVar9 = 0;
      do {
        uVar6 = FUN_00003fc8(iVar10,lVar9);
        if (((uint)abStack_50[(int)uVar6 >> 3] & 1 << (uVar6 & 7)) != 0) {
          uVar8 = uVar8 | 1 << ((uint)lVar9 & 0x3f);
        }
        lVar9 = lVar9 + 1;
      } while ((int)lVar9 < 4);
      if (uVar8 == uVar5) {
        *(undefined4 *)(PTR_DAT_00012d58 + iVar10 * 4) = 1;
      }
      else if (uVar8 != 0) {
                    /* WARNING: Subroutine does not return */
        FUN_00006ac0("%s:%u: failed assertion `%s\'\n","../game.c",0x34a,"0");
      }
      iVar10 = iVar10 + 1;
    } while (iVar10 < 0x40);
LAB_000042dc:
    pvVar7 = (void *)_fread(local_30,1,1,pFVar3);
    bVar2 = local_30[0];
    puVar1 = PTR_DAT_00012d50;
    if (pvVar7 == (void *)0x1) {
      pvVar7 = _malloc(0x1644);
      *(void **)(puVar1 + (uint)bVar2 * 4) = pvVar7;
      uVar5 = 0;
      iVar10 = 0;
      _memset(*(void **)(puVar1 + (uint)local_30[0] * 4),0,0x1644);
      do {
        puVar1 = PTR_DAT_00012d50;
        sVar4 = _fread((void *)(*(int *)(PTR_DAT_00012d50 + (uint)local_30[0] * 4) + iVar10),3,1,
                       pFVar3);
        if (sVar4 != 1) {
          _free(*(void **)(puVar1 + (uint)local_30[0] * 4));
          *(undefined4 *)(puVar1 + (uint)local_30[0] * 4) = 0;
          break;
        }
        uVar5 = uVar5 + 1;
        iVar10 = iVar10 + 0x14;
      } while (uVar5 < 0x11d);
      goto LAB_000042dc;
    }
  }
  if (pFVar3 != (FILE *)0x0) {
    pvVar7 = (void *)_fclose(pFVar3);
  }
  FUN_00004050(pvVar7);
  return;
}



// Function: FUN_0000433c @ 0x0000433c

int FUN_0000433c(void)

{
  void *pvVar1;
  undefined *puVar2;
  FILE *pFVar3;
  int iVar4;
  uint uVar5;
  int iVar6;
  longlong lVar7;
  void *pvVar8;
  void *pvVar9;
  byte abStack_50 [32];
  undefined1 local_30 [48];
  
  pFVar3 = _fopen("com.silverspaceship.chromatron.dat","wb");
  iVar6 = 0;
  if (pFVar3 != (FILE *)0x0) {
    _memset(abStack_50,0,0x20);
    iVar6 = 0;
    do {
      if (*(int *)(PTR_DAT_00012d58 + iVar6 * 4) != 0) {
        iVar4 = FUN_0000400c(iVar6);
        lVar7 = 0;
        do {
          if ((iVar4 >> ((uint)lVar7 & 0x3f) & 1U) != 0) {
            uVar5 = FUN_00003fc8(iVar6,lVar7);
            abStack_50[(int)uVar5 >> 3] = abStack_50[(int)uVar5 >> 3] | (byte)(1 << (uVar5 & 7));
          }
          lVar7 = lVar7 + 1;
        } while ((int)lVar7 < 4);
      }
      iVar6 = iVar6 + 1;
    } while (iVar6 < 0x40);
    _fwrite(abStack_50,1,0x20,pFVar3);
    iVar6 = 0;
    do {
      puVar2 = PTR_DAT_00012d50;
      if (*(int *)(PTR_DAT_00012d50 + iVar6 * 4) != 0) {
        local_30[0] = (undefined1)iVar6;
        _fwrite(local_30,1,1,pFVar3);
        pvVar1 = *(void **)(puVar2 + iVar6 * 4);
        pvVar8 = pvVar1;
        do {
          pvVar9 = (void *)((int)pvVar8 + 0x14);
          _fwrite(pvVar8,3,1,pFVar3);
          pvVar8 = pvVar9;
        } while (pvVar9 <= (void *)((int)pvVar1 + 0x1630U));
      }
      iVar6 = iVar6 + 1;
    } while (iVar6 < 0x80);
    iVar6 = _fclose(pFVar3);
  }
  return iVar6;
}



// Function: FUN_00004494 @ 0x00004494

void FUN_00004494(void)

{
  undefined *puVar1;
  longlong lVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  longlong lVar6;
  int iVar7;
  
  FUN_00003ea4();
  iVar3 = 0;
  iVar4 = 0;
  *(undefined4 *)PTR_DAT_00012d4c = 1;
  do {
    iVar5 = 0;
    iVar7 = iVar4;
    do {
      lVar6 = 7;
      do {
        if (PTR_DAT_00012d6c[iVar7] == '\n') {
          lVar2 = FUN_00003ecc(PTR_DAT_00012d6c + iVar7);
          if (lVar2 == 0) {
            *(undefined4 *)PTR_DAT_00012d4c = 0;
          }
        }
        puVar1 = PTR_DAT_00012d48;
        lVar6 = lVar6 + -1;
      } while (-1 < lVar6);
      iVar5 = iVar5 + 1;
      iVar7 = iVar7 + 0x14;
    } while (iVar5 < 0xf);
    iVar3 = iVar3 + 1;
    iVar4 = iVar4 + 300;
  } while (iVar3 < 0xf);
  if (*(int *)PTR_DAT_00012d48 != 0) {
    *(undefined4 *)PTR_DAT_00012d4c = 1;
    *(undefined4 *)puVar1 = 0;
  }
  if ((*(int *)PTR_DAT_00012d44 != 0) && (*(int *)PTR_DAT_00012d4c != 0)) {
    if (*(int *)(PTR_DAT_00012d58 + DAT_0000803c * 4) == 0) {
      *(undefined4 *)(PTR_DAT_00012d58 + DAT_0000803c * 4) = 1;
      FUN_000055f4();
      FUN_0000433c();
      FUN_00004050();
      return;
    }
  }
  return;
}



// Function: FUN_000045d4 @ 0x000045d4

longlong FUN_000045d4(undefined1 *param_1)

{
  byte bVar1;
  ulonglong uVar2;
  byte bVar3;
  byte *pbVar4;
  longlong lVar5;
  ulonglong uVar6;
  longlong lVar7;
  
  uVar6 = (ulonglong)(byte)param_1[2];
  uVar2 = uVar6 & 3;
  lVar5 = -1;
  switch(*param_1) {
  case 0:
    lVar5 = 0;
    break;
  case 1:
    lVar5 = 1;
    break;
  case 2:
    bVar3 = param_1[1];
    if (bVar3 == 2) {
      lVar5 = uVar6 + 0x48;
    }
    else if (bVar3 < 3) {
      if (bVar3 == 1) {
        lVar5 = uVar6 + 0x58;
      }
    }
    else if (bVar3 == 4) {
      lVar5 = uVar6 + 0x38;
    }
    else if (bVar3 == 7) {
      lVar5 = uVar6 + 0x68;
    }
    break;
  case 3:
    lVar5 = uVar6 + 0x20;
    break;
  case 4:
    lVar5 = uVar6 + 0x30;
    break;
  case 5:
    bVar3 = param_1[1];
    if (bVar3 == 2) {
      lVar5 = uVar2 + 0x70;
    }
    else if (bVar3 < 3) {
      if (bVar3 == 1) {
        lVar5 = uVar2 + 8;
      }
    }
    else if (bVar3 == 4) {
      lVar5 = uVar2 + 0x60;
    }
    break;
  case 6:
    lVar5 = uVar6 + 0x18;
    break;
  case 7:
    lVar5 = uVar6 + 0x40;
    break;
  case 8:
    lVar5 = uVar2 + 0x28;
    break;
  case 9:
    lVar5 = uVar6 + 0x50;
    break;
  case 10:
    switch(param_1[1]) {
    case 0:
      lVar5 = 0xc;
      break;
    case 1:
      lVar5 = 6;
      break;
    case 2:
      lVar5 = 4;
      break;
    case 3:
      lVar5 = 0x12;
      break;
    case 4:
      lVar5 = 2;
      break;
    case 5:
      lVar5 = 0x14;
      break;
    case 6:
      lVar5 = 0x10;
      break;
    case 7:
      lVar5 = 0x16;
    }
    pbVar4 = param_1 + 4;
    lVar7 = 8;
    bVar3 = 0;
    do {
      bVar1 = *pbVar4;
      pbVar4 = pbVar4 + 1;
      bVar3 = bVar3 | bVar1;
      lVar7 = lVar7 + -1;
    } while (lVar7 != 0);
    if (param_1[1] == bVar3) {
      lVar5 = lVar5 + 1;
    }
    break;
  case 0xb:
    lVar5 = uVar2 + 0x2c;
    break;
  case 0xc:
    lVar5 = 0xe;
  }
  return lVar5;
}



// Function: FUN_000047e0 @ 0x000047e0

void FUN_000047e0(longlong param_1,int param_2,int param_3,longlong param_4,int param_5,int param_6,
                 int param_7,int param_8)

{
  byte bVar1;
  undefined1 uVar2;
  undefined1 uVar3;
  int iVar4;
  int iVar5;
  undefined *puVar6;
  int iVar7;
  int iVar8;
  byte *pbVar9;
  int iVar10;
  int iVar11;
  longlong lVar12;
  
  if (param_1 < 0) {
    param_4 = param_4 + param_1;
    param_1 = 0;
  }
  if (param_2 < 0) {
    param_5 = param_5 + param_2;
    param_2 = 0;
  }
  if ((int)DAT_00012dd0 < (int)param_1 + (int)param_4) {
    param_4 = (ulonglong)DAT_00012dd0 - param_1;
  }
  if (DAT_00012dd4 < param_2 + param_5) {
    param_5 = DAT_00012dd4 - param_2;
  }
  iVar11 = 0;
  if (0 < param_5) {
    iVar10 = 0;
    do {
      puVar6 = PTR_DAT_00012d40;
      iVar8 = 0;
      if (0 < (int)param_4) {
        pbVar9 = (byte *)(iVar10 + param_3);
        lVar12 = param_4;
        do {
          bVar1 = *pbVar9;
          pbVar9 = pbVar9 + 1;
          iVar5 = (DAT_00012dd0 * (iVar11 + param_2) + iVar8 + (int)param_1) * 3;
          iVar4 = iVar5 + DAT_00012dcc;
          if (param_7 <= (int)(uint)bVar1) {
            iVar7 = ((uint)bVar1 + param_8) * 3;
            uVar2 = puVar6[iVar7 + 2];
            uVar3 = puVar6[iVar7 + 1];
            *(undefined *)(iVar5 + DAT_00012dcc) = puVar6[iVar7];
            *(undefined1 *)(iVar4 + 2) = uVar2;
            *(undefined1 *)(iVar4 + 1) = uVar3;
          }
          iVar8 = iVar8 + 1;
          lVar12 = lVar12 + -1;
        } while (lVar12 != 0);
      }
      iVar11 = iVar11 + 1;
      iVar10 = iVar10 + param_6;
    } while (iVar11 < param_5);
  }
  return;
}



// Function: FUN_00004908 @ 0x00004908

void FUN_00004908(undefined8 param_1,int param_2,int param_3,int param_4)

{
  undefined1 *puVar1;
  int iVar2;
  
  iVar2 = param_3;
  if (param_4 < param_3) {
    iVar2 = param_4;
    param_4 = param_3;
  }
  puVar1 = (undefined1 *)(DAT_00012dcc + (param_2 * DAT_00012dd0 + iVar2) * 3);
  if (param_4 < iVar2) {
    return;
  }
  iVar2 = (param_4 + 1) - iVar2;
  do {
    *puVar1 = (char)((ulonglong)param_1 >> 0x10);
    puVar1[1] = (char)((ulonglong)param_1 >> 8);
    puVar1[2] = (char)param_1;
    puVar1 = puVar1 + 3;
    iVar2 = iVar2 + -1;
  } while (iVar2 != 0);
  return;
}



// Function: FUN_00004980 @ 0x00004980

void FUN_00004980(undefined8 param_1,int param_2,longlong param_3,longlong param_4)

{
  longlong lVar1;
  undefined1 *puVar2;
  
  lVar1 = param_3;
  if ((int)param_4 < (int)param_3) {
    lVar1 = param_4;
    param_4 = param_3;
  }
  puVar2 = (undefined1 *)(DAT_00012dcc + ((int)lVar1 * DAT_00012dd0 + param_2) * 3);
  if ((int)param_4 < (int)lVar1) {
    return;
  }
  lVar1 = (param_4 + 1) - lVar1;
  do {
    *puVar2 = (char)((ulonglong)param_1 >> 0x10);
    puVar2[1] = (char)((ulonglong)param_1 >> 8);
    puVar2[2] = (char)param_1;
    puVar2 = puVar2 + DAT_00012dd0 * 3;
    lVar1 = lVar1 + -1;
  } while (lVar1 != 0);
  return;
}



// Function: FUN_00004a08 @ 0x00004a08

void FUN_00004a08(undefined8 param_1,int param_2,int param_3,int param_4,int param_5)

{
  int iVar1;
  undefined1 *puVar2;
  
  iVar1 = param_2;
  if (param_4 < param_2) {
    param_3 = param_5;
    iVar1 = param_4;
    param_4 = param_2;
  }
  puVar2 = (undefined1 *)(DAT_00012dcc + (param_3 * DAT_00012dd0 + iVar1) * 3);
  if (param_4 < iVar1) {
    return;
  }
  iVar1 = (param_4 + 1) - iVar1;
  do {
    *puVar2 = (char)((ulonglong)param_1 >> 0x10);
    puVar2[1] = (char)((ulonglong)param_1 >> 8);
    puVar2[2] = (char)param_1;
    puVar2 = puVar2 + DAT_00012dd0 * 3 + 3;
    iVar1 = iVar1 + -1;
  } while (iVar1 != 0);
  return;
}



// Function: FUN_00004a98 @ 0x00004a98

void FUN_00004a98(undefined8 param_1,int param_2,longlong param_3,int param_4,longlong param_5)

{
  longlong lVar1;
  undefined1 *puVar2;
  
  lVar1 = param_3;
  if ((int)param_5 < (int)param_3) {
    lVar1 = param_5;
    param_5 = param_3;
    param_2 = param_4;
  }
  puVar2 = (undefined1 *)(DAT_00012dcc + ((int)lVar1 * DAT_00012dd0 + param_2) * 3);
  if ((int)param_5 < (int)lVar1) {
    return;
  }
  lVar1 = (param_5 + 1) - lVar1;
  do {
    *puVar2 = (char)((ulonglong)param_1 >> 0x10);
    puVar2[1] = (char)((ulonglong)param_1 >> 8);
    puVar2[2] = (char)param_1;
    puVar2 = puVar2 + DAT_00012dd0 * 3 + -3;
    lVar1 = lVar1 + -1;
  } while (lVar1 != 0);
  return;
}



// Function: FUN_00004b28 @ 0x00004b28

void FUN_00004b28(undefined8 param_1,undefined8 param_2,undefined8 param_3,int param_4,int param_5)

{
  int iVar1;
  
  if ((int)param_2 == param_4) {
    FUN_00004980();
    return;
  }
  iVar1 = (int)param_3;
  if (iVar1 == param_5) {
    FUN_00004908(param_1,param_3,param_2);
    return;
  }
  param_4 = param_4 - (int)param_2;
  if (param_4 == param_5 - iVar1) {
    FUN_00004a08();
    return;
  }
  if (param_4 == iVar1 - param_5) {
    FUN_00004a98();
    return;
  }
                    /* WARNING: Subroutine does not return */
  FUN_00006ac0("%s:%u: failed assertion `%s\'\n","../game.c",0x4a4,"0");
}



// Function: FUN_00004bec @ 0x00004bec

void FUN_00004bec(int *param_1,int *param_2,int *param_3,int *param_4)

{
  int iVar1;
  int iVar2;
  int iVar3;
  longlong lVar4;
  int iVar5;
  
  iVar3 = 0x18;
  iVar2 = 0x18;
  lVar4 = (ulonglong)*(uint *)PTR_DAT_00012d3c - 0xc;
  iVar5 = *(int *)PTR_DAT_00012d38 + -0xc;
  if (lVar4 < 0) {
    iVar3 = *(uint *)PTR_DAT_00012d3c + 0xc;
    lVar4 = 0;
  }
  if (iVar5 < 0) {
    iVar2 = *(int *)PTR_DAT_00012d38 + 0xc;
    iVar5 = 0;
  }
  iVar1 = (int)lVar4;
  if (DAT_00012dd0 < iVar1 + iVar3) {
    iVar3 = DAT_00012dd0 - iVar1;
  }
  if (DAT_00012dd4 < iVar5 + iVar2) {
    iVar2 = DAT_00012dd4 - iVar5;
  }
  *param_1 = iVar1;
  *param_2 = iVar5;
  *param_3 = iVar3;
  *param_4 = iVar2;
  return;
}



// Function: FUN_00004c8c @ 0x00004c8c

void * FUN_00004c8c(void *param_1,int param_2,int param_3,int param_4,int param_5,longlong param_6)

{
  int iVar1;
  int iVar2;
  void *pvVar3;
  int iVar4;
  int iVar5;
  
  pvVar3 = param_1;
  if (0 < param_6) {
    iVar4 = 0;
    iVar5 = 0;
    do {
      iVar1 = iVar5 * 3;
      iVar5 = iVar5 + param_2;
      iVar2 = iVar4 * 3;
      iVar4 = iVar4 + param_4;
      pvVar3 = _memcpy((void *)(iVar1 + (int)param_1),(void *)(iVar2 + param_3),param_5 * 3);
      param_6 = param_6 + -1;
    } while (param_6 != 0);
  }
  return pvVar3;
}



// Function: FUN_00004d00 @ 0x00004d00

void FUN_00004d00(void)

{
  uint local_20;
  int local_1c;
  undefined4 local_18;
  undefined4 local_14 [5];
  
  FUN_00004bec(&local_20,&local_1c,&local_18,local_14);
  FUN_00004c8c(&DAT_00012dd8,0x20,
               ((longlong)local_1c * (longlong)DAT_00012dd0 + (ulonglong)local_20) * 3 +
               (ulonglong)DAT_00012dcc,DAT_00012dd0,local_18,local_14[0]);
  return;
}



// Function: FUN_00004e00 @ 0x00004e00

void FUN_00004e00(void)

{
  FUN_000047e0((ulonglong)*(uint *)PTR_DAT_00012d3c - 0xc,(ulonglong)*(uint *)PTR_DAT_00012d38 - 0xc
               ,*(undefined4 *)(PTR_DAT_00012d34 + DAT_000080d0 * 4),0x18,0x18,0x18,0xe,0);
  return;
}



// Function: FUN_00004e68 @ 0x00004e68

/* WARNING: Restarted to delay deadcode elimination for space: stack */

void FUN_00004e68(void)

{
  uint local_20;
  int local_1c;
  undefined4 local_18;
  undefined4 local_14 [5];
  
  if (-1 < DAT_000080d0) {
    FUN_00004d00();
    FUN_00004e00();
  }
  FUN_000030cc(0,0,DAT_00012dcc,DAT_00012dd0,DAT_00012dd4,DAT_00012dd0);
  if (-1 < DAT_000080d0) {
    FUN_00004bec(&local_20,&local_1c,&local_18,local_14);
    FUN_00004c8c(((longlong)local_1c * (longlong)DAT_00012dd0 + (ulonglong)local_20) * 3 +
                 (ulonglong)DAT_00012dcc,DAT_00012dd0,&DAT_00012dd8,0x20,local_18,local_14[0]);
    return;
  }
  return;
}



// Function: FUN_00004f14 @ 0x00004f14

void FUN_00004f14(void)

{
  FUN_00004494();
  FUN_000034b8(0,0,0x280,0x1e0);
  return;
}



// Function: FUN_00004f4c @ 0x00004f4c

void FUN_00004f4c(void)

{
  int iVar1;
  int iVar2;
  int iVar3;
  longlong lVar4;
  undefined *puVar5;
  
  iVar1 = *(int *)PTR_DAT_00012d2c;
  iVar2 = *(int *)PTR_DAT_00012d30;
  iVar3 = iVar1 * 300 + iVar2 * 0x14;
  puVar5 = PTR_DAT_00012d6c + iVar3;
  lVar4 = FUN_000034d8(PTR_DAT_00012d6c[iVar3]);
  if (lVar4 == 0) {
    DAT_00012db0 = 0;
  }
  else {
    DAT_000139e0 = iVar2 * 0x18 + 0x3c;
    DAT_000139e4 = iVar1 * 0x18 + 0x1e;
    DAT_00012db0 = 2;
    DAT_000080d0 = FUN_000045d4(puVar5);
    iVar1 = DAT_000139e4;
    *(int *)PTR_DAT_00012d3c = DAT_000139e0;
    *(int *)PTR_DAT_00012d38 = iVar1;
  }
  return;
}



// Function: FUN_000050d4 @ 0x000050d4

void FUN_000050d4(int param_1,longlong param_2,longlong param_3)

{
  undefined4 uVar1;
  undefined1 uVar5;
  uint uVar6;
  undefined *puVar7;
  undefined4 *puVar8;
  undefined4 *puVar9;
  int iVar10;
  int iVar11;
  uint uVar13;
  longlong lVar12;
  ulonglong uVar14;
  undefined4 uVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  
  puVar7 = PTR_DAT_00012d6c;
  uVar13 = (uint)param_2;
  uVar6 = (uint)param_3;
  uVar14 = ((longlong)((int)uVar13 / 0x18 + ((int)uVar13 >> 0x1f)) - (longlong)((int)uVar13 >> 0x1f)
           ) - 2;
  iVar10 = (int)(uVar6 + 0x1e) / 0x18 + -2;
  if (((0xe < (uVar14 & 0xffffffff)) || (iVar10 < 0)) || (0xe < iVar10)) {
    iVar10 = (int)(uVar13 - 0x1a6) >> 0x1f;
    iVar11 = (int)(uVar6 + 0x12) >> 0x1f;
    uVar14 = ((longlong)((int)(uVar13 - 0x1a6) / 0x1a + iVar10) - (longlong)iVar10) - 1;
    lVar12 = ((longlong)((int)(uVar6 + 0x12) / 0x1a + iVar11) - (longlong)iVar11) + -1;
    if ((((uVar14 & 0xffffffff) < 6) && (iVar10 = (int)lVar12, -1 < iVar10)) && (iVar10 < 4)) {
      lVar12 = lVar12 * 6;
      iVar10 = 0xf;
    }
    else {
      iVar10 = (int)(uVar13 + 10) >> 0x1f;
      iVar11 = (int)(uVar6 - 0x186) >> 0x1f;
      uVar14 = ((longlong)((int)(uVar13 + 10) / 0x14 + iVar10) - (longlong)iVar10) - 1;
      lVar12 = ((longlong)((int)(uVar6 - 0x186) / 0x14 + iVar11) - (longlong)iVar11) + -1;
      if (((0x18 < (uVar14 & 0xffffffff)) || (iVar10 = (int)lVar12, iVar10 < 0)) || (1 < iVar10)) {
        iVar10 = -1;
        goto LAB_00005204;
      }
      lVar12 = lVar12 * 0x19;
      iVar10 = -2;
    }
    uVar14 = uVar14 + lVar12;
  }
LAB_00005204:
  iVar11 = (int)uVar14;
  if (*(int *)PTR_DAT_00012d44 == 0) {
    if (((((uVar14 & 0xffffffff) < 0xf) && (-1 < iVar10)) && (iVar10 < 0xf)) &&
       ((param_1 == 1 || (param_1 == 4)))) {
      *(int *)PTR_DAT_00012d30 = iVar11;
      *(int *)PTR_DAT_00012d2c = iVar10;
    }
  }
  else if (param_1 == 0) {
    if (DAT_00012db0 != 0) {
      if (DAT_00012db0 == 1) {
        if (((((ulonglong)DAT_000139d8 - param_2) + 1 & 0xffffffff) < 3) &&
           ((((ulonglong)DAT_000139dc - param_3) + 1 & 0xffffffff) < 3)) {
          return;
        }
        if (iVar10 < 0) {
          return;
        }
        FUN_00004f4c();
      }
      FUN_000034b8((ulonglong)DAT_000139e0 - 0x1e,(ulonglong)DAT_000139e4 - 0x1e,0x3c,0x3c);
      DAT_000139e0 = uVar13;
      DAT_000139e4 = uVar6;
      FUN_000034b8(param_2 + -0xc,param_3 + -0xc,0x19,0x19);
      *(uint *)PTR_DAT_00012d3c = uVar13;
      *(uint *)PTR_DAT_00012d38 = uVar6;
    }
  }
  else if (iVar10 < 0) {
    if (param_1 == 4) {
      if (DAT_00012db0 == 2) {
        uVar14 = 0xffffffffffffffff;
        iVar10 = -1;
        goto LAB_00005444;
      }
      if ((iVar10 == -2) && (*(int *)(PTR_DAT_00012d54 + (int)((uVar14 & 0xffffffff) << 2)) != 0)) {
        FUN_00005714(uVar14);
        return;
      }
    }
  }
  else if (param_1 == 4) {
    if (DAT_00012db0 == 2) {
LAB_00005444:
      if (((-1 < (longlong)uVar14) && (-1 < iVar10)) &&
         (iVar10 = iVar10 * 300 + (int)uVar14 * 0x14,
         puVar9 = (undefined4 *)(PTR_DAT_00012d6c + iVar10), PTR_DAT_00012d6c[iVar10] == '\0')) {
        iVar10 = *(int *)PTR_DAT_00012d2c * 300 + *(int *)PTR_DAT_00012d30 * 0x14;
        puVar8 = (undefined4 *)(PTR_DAT_00012d6c + iVar10);
        uVar1 = puVar8[1];
        uVar2 = puVar8[2];
        uVar3 = puVar8[3];
        uVar4 = puVar8[4];
        *puVar9 = *puVar8;
        puVar9[1] = uVar1;
        puVar9[2] = uVar2;
        puVar9[3] = uVar3;
        puVar9[4] = uVar4;
        puVar7[iVar10] = 0;
      }
      FUN_00004f14();
      DAT_00012db0 = 0;
      DAT_000080d0 = 0xffffffff;
      return;
    }
    iVar10 = iVar10 * 300 + iVar11 * 0x14;
    iVar11 = FUN_000034d8(PTR_DAT_00012d6c[iVar10]);
    if (iVar11 != 0) {
      puVar7[iVar10 + 2] = puVar7[iVar10 + 2] + -1;
      puVar7[iVar10 + 2] = puVar7[iVar10 + 2] & 7;
      FUN_00004f14();
      DAT_00012db0 = 0;
    }
  }
  else if (param_1 < 5) {
    if (param_1 == 1) {
      uVar5 = PTR_DAT_00012d6c[iVar10 * 300 + iVar11 * 0x14];
      *(int *)PTR_DAT_00012d30 = iVar11;
      *(int *)PTR_DAT_00012d2c = iVar10;
      iVar10 = FUN_000034d8(uVar5);
      if (iVar10 != 0) {
        DAT_00012db0 = 1;
        DAT_000139d8 = uVar13;
        DAT_000139dc = uVar6;
      }
    }
  }
  else if ((param_1 == 6) && (DAT_00012db0 == 0)) {
    iVar10 = iVar10 * 300 + iVar11 * 0x14;
    iVar11 = FUN_000034d8(PTR_DAT_00012d6c[iVar10]);
    if (iVar11 != 0) {
      puVar7[iVar10 + 2] = puVar7[iVar10 + 2] + '\x01';
      puVar7[iVar10 + 2] = puVar7[iVar10 + 2] & 7;
      FUN_00004f14();
      return;
    }
  }
  return;
}



// Function: FUN_000054f8 @ 0x000054f8

void FUN_000054f8(void)

{
  undefined4 uVar1;
  undefined *puVar5;
  undefined *puVar6;
  char *pcVar7;
  undefined4 *puVar8;
  int iVar9;
  int iVar10;
  int iVar11;
  longlong lVar12;
  int iVar13;
  int iVar14;
  char *pcVar15;
  undefined4 uVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  
  iVar10 = 0;
  iVar14 = 0;
  pcVar15 = PTR_DAT_00012d6c + 0x1194;
  iVar11 = 0;
  lVar12 = 0xe0;
  iVar13 = 0;
  do {
    puVar5 = PTR_DAT_00012d6c;
    iVar9 = FUN_000034d8(PTR_DAT_00012d6c[iVar14]);
    puVar6 = PTR_DAT_00012d6c;
    if (iVar9 != 0) {
      if (*pcVar15 != '\0') {
        pcVar7 = puVar5 + iVar13 + 0x1194;
        do {
          pcVar7 = pcVar7 + 0x14;
          iVar10 = iVar10 + 1;
          iVar13 = iVar13 + 0x14;
          pcVar15 = pcVar15 + 0x14;
          iVar11 = iVar11 + 0x14;
        } while (*pcVar7 != '\0');
      }
      puVar8 = (undefined4 *)(PTR_DAT_00012d6c + iVar14);
      uVar1 = puVar8[1];
      uVar2 = puVar8[2];
      uVar3 = puVar8[3];
      uVar4 = puVar8[4];
      *(undefined4 *)(PTR_DAT_00012d6c + iVar11 + 0x1194) = *puVar8;
      *(undefined4 *)(puVar6 + iVar11 + 0x1198) = uVar1;
      *(undefined4 *)(puVar6 + iVar11 + 0x119c) = uVar2;
      *(undefined4 *)(puVar6 + iVar11 + 0x11a0) = uVar3;
      *(undefined4 *)(puVar6 + iVar11 + 0x11a4) = uVar4;
      puVar6[iVar11 + 0x1196] = 0;
      puVar6[iVar14] = 0;
    }
    lVar12 = lVar12 + -1;
    iVar14 = iVar14 + 0x14;
  } while (-1 < lVar12);
  _qsort(PTR_DAT_00012d6c + 0x1194,iVar10 + 1,0x14,DAT_0000810c);
  FUN_00004494();
  FUN_000034b8(0,0,0x280,0x1e0);
  return;
}



// Function: FUN_000055f4 @ 0x000055f4

void * FUN_000055f4(void)

{
  int iVar1;
  undefined *puVar2;
  undefined *puVar3;
  void *pvVar4;
  
  puVar3 = PTR_DAT_00012d50;
  puVar2 = PTR_DAT_00012d28;
  iVar1 = *(int *)PTR_DAT_00012d28;
  if (*(int *)(PTR_DAT_00012d50 + iVar1 * 4) == 0) {
    pvVar4 = _malloc(0x1644);
    *(void **)(puVar3 + iVar1 * 4) = pvVar4;
  }
  pvVar4 = _memcpy(*(void **)(puVar3 + *(int *)puVar2 * 4),PTR_DAT_00012d6c,0x1644);
  return pvVar4;
}



// Function: FUN_00005668 @ 0x00005668

void FUN_00005668(int param_1)

{
  void *pvVar1;
  
  FUN_000069fc();
  if ((param_1 == 0) || (*(void **)(PTR_DAT_00012d50 + *(int *)PTR_DAT_00012d28 * 4) == (void *)0x0)
     ) {
    FUN_000054f8();
  }
  else {
    pvVar1 = _memcpy(PTR_DAT_00012d6c,*(void **)(PTR_DAT_00012d50 + *(int *)PTR_DAT_00012d28 * 4),
                     0x1644);
    FUN_00004494(pvVar1);
  }
  *(undefined4 *)PTR_DAT_00012d44 = 2;
  *(undefined4 *)PTR_DAT_00012d24 = 1;
  FUN_000034b8(0,0,0x280,0x1e0);
  return;
}



// Function: FUN_00005714 @ 0x00005714

void FUN_00005714(int param_1)

{
  FUN_000055f4();
  *(uint *)PTR_DAT_00012d28 = (uint)(byte)PTR_DAT_00012d20[param_1];
  DAT_0000803c = param_1;
  FUN_00005668(1);
  return;
}



// Function: FUN_0000576c @ 0x0000576c

void FUN_0000576c(void)

{
  DAT_0000803c = DAT_0000803c + 1;
  *(uint *)PTR_DAT_00012d28 = (uint)(byte)PTR_DAT_00012d20[DAT_0000803c];
  return;
}



// Function: FUN_000057ac @ 0x000057ac

undefined4 FUN_000057ac(void)

{
  if (0 < DAT_0000803c) {
    DAT_0000803c = DAT_0000803c + -1;
    *(uint *)PTR_DAT_00012d28 = (uint)(byte)PTR_DAT_00012d20[DAT_0000803c];
  }
  return *(undefined4 *)PTR_DAT_00012d28;
}



// Function: FUN_00005800 @ 0x00005800

void FUN_00005800(void)

{
  undefined *puVar1;
  undefined4 uVar2;
  
  FUN_000055f4();
  puVar1 = PTR_DAT_00012d28;
  if (DAT_0000803c < 0x31) {
    uVar2 = FUN_0000576c(*(undefined4 *)PTR_DAT_00012d28);
    *(undefined4 *)puVar1 = uVar2;
  }
  FUN_00005668(1);
  return;
}



// Function: FUN_00005858 @ 0x00005858

void FUN_00005858(void)

{
  undefined *puVar1;
  undefined4 uVar2;
  
  FUN_000055f4();
  puVar1 = PTR_DAT_00012d28;
  uVar2 = FUN_000057ac(*(undefined4 *)PTR_DAT_00012d28);
  *(undefined4 *)puVar1 = uVar2;
  FUN_00005668(1);
  return;
}



// Function: FUN_000058e4 @ 0x000058e4

longlong FUN_000058e4(longlong param_1)

{
  longlong lVar1;
  
  lVar1 = param_1 + 0x27;
  if ((int)param_1 < 0x1a) {
    lVar1 = param_1 + 0x61;
  }
  return lVar1;
}



// Function: FUN_000058fc @ 0x000058fc

longlong FUN_000058fc(longlong param_1)

{
  longlong lVar1;
  
  lVar1 = param_1 + -0x27;
  if (0x5a < (int)param_1) {
    lVar1 = param_1 + -0x61;
  }
  return lVar1;
}



// Function: FUN_00005914 @ 0x00005914

undefined1 * FUN_00005914(void)

{
  byte bVar1;
  byte bVar2;
  ushort *puVar3;
  byte *pbVar4;
  char cVar5;
  undefined *puVar6;
  int iVar7;
  undefined1 uVar9;
  undefined1 *puVar8;
  int iVar10;
  short sVar11;
  int iVar12;
  size_t sVar13;
  int iVar14;
  longlong lVar15;
  int iVar17;
  longlong lVar16;
  int iVar18;
  ushort local_1a0;
  byte local_19e [414];
  
  sVar13 = 0;
  iVar10 = 0;
  sVar11 = 0;
  iVar12 = 0;
  do {
    iVar17 = sVar13 * 6;
    iVar14 = 0;
    iVar18 = iVar12;
    do {
      puVar6 = PTR_DAT_00012d6c;
      bVar2 = PTR_DAT_00012d6c[iVar18];
      iVar7 = FUN_000034d8(bVar2);
      if (iVar7 != 0) {
        *(short *)((int)&local_1a0 + iVar17) = sVar11 + (short)iVar14;
        bVar1 = puVar6[iVar18 + 2];
        sVar13 = sVar13 + 1;
        local_19e[iVar17 + 1] = bVar2;
        local_19e[iVar17] = bVar1;
        local_19e[iVar17 + 2] = puVar6[iVar18 + 1];
        iVar17 = iVar17 + 6;
      }
      iVar14 = iVar14 + 1;
      iVar18 = iVar18 + 0x14;
    } while (iVar14 < 0xf);
    iVar10 = iVar10 + 1;
    iVar12 = iVar12 + 300;
    sVar11 = sVar11 + 0xf;
  } while (iVar10 < 0x13);
  _qsort(&local_1a0,sVar13,6,(int *)PTR_LAB_00008108);
  puVar8 = (undefined1 *)0x0;
  if (sVar13 * 2 + 6 < 0x37) {
    DAT_000139ec = 0x2d;
    DAT_000139e9 = 0x2d;
    iVar10 = 5;
    cVar5 = (char)((DAT_0000803c + 1) / 10);
    DAT_000139ea = cVar5 + '0';
    DAT_000139eb = (char)(DAT_0000803c + 1) + cVar5 * -10 + '0';
    DAT_000139e8 = 0x31;
    if (0 < (int)sVar13) {
      iVar12 = 0;
      do {
        puVar3 = (ushort *)((int)&local_1a0 + iVar12);
        pbVar4 = local_19e + iVar12;
        iVar12 = iVar12 + 6;
        lVar15 = (ulonglong)*puVar3 + (ulonglong)*pbVar4 * 0x11d;
        lVar16 = (longlong)(int)((uint)lVar15 / 0x34);
        uVar9 = FUN_000058e4(lVar16);
        (&DAT_000139e8)[iVar10] = uVar9;
        uVar9 = FUN_000058e4(lVar15 + lVar16 * -0x34);
        sVar13 = sVar13 - 1;
        (&DAT_000139e9)[iVar10] = uVar9;
        iVar10 = iVar10 + 2;
      } while (sVar13 != 0);
    }
    (&DAT_000139e8)[iVar10] = 0;
    puVar8 = &DAT_000139e8;
  }
  return puVar8;
}



// Function: FUN_00005ad4 @ 0x00005ad4

void FUN_00005ad4(char *param_1)

{
  char cVar1;
  undefined1 uVar2;
  undefined1 uVar3;
  ushort uVar4;
  undefined *puVar5;
  size_t sVar6;
  int iVar7;
  int iVar8;
  int iVar9;
  int iVar10;
  int iVar11;
  int iVar12;
  short sVar13;
  longlong lVar14;
  ushort local_1a0;
  undefined1 local_19e [414];
  
  iVar12 = 0;
  if (param_1 != (char *)0x0) {
    cVar1 = *param_1;
    while (cVar1 == ' ') {
      param_1 = param_1 + 1;
      cVar1 = *param_1;
    }
    if (((((*param_1 == '1') && (param_1[1] == '-')) && ((byte)param_1[2] - 0x30 < 10)) &&
        (((byte)param_1[3] - 0x30 < 10 && (param_1[4] == '-')))) &&
       ((param_1[2] * 10 + (int)param_1[3] + -0x210 == DAT_0000803c + 1 &&
        (param_1 = param_1 + 5, *param_1 != ' ')))) {
      while (sVar6 = _strlen(param_1), param_1[sVar6 - 1] == ' ') {
        sVar6 = _strlen(param_1);
        param_1[sVar6 - 1] = '\0';
      }
      iVar11 = 0;
      iVar8 = 0;
      do {
        lVar14 = 0xe;
        iVar9 = iVar8;
        do {
          iVar7 = FUN_000034d8(PTR_DAT_00012d6c[iVar9]);
          if (iVar7 != 0) {
            iVar12 = iVar12 + 1;
          }
          lVar14 = lVar14 + -1;
          iVar9 = iVar9 + 0x14;
        } while (-1 < lVar14);
        iVar11 = iVar11 + 1;
        iVar8 = iVar8 + 300;
      } while (iVar11 < 0x13);
      sVar6 = _strlen(param_1);
      if (sVar6 == iVar12 << 1) {
        iVar11 = 0;
        if (0 < iVar12) {
          do {
            iVar8 = FUN_000058fc(param_1[iVar11 * 2]);
            iVar9 = FUN_000058fc(param_1[iVar11 * 2 + 1]);
            if ((PTR_DAT_00012d6c[((iVar8 * 0x34 + iVar9) % 0x11d) * 0x14] != '\0') &&
               (iVar8 = FUN_000034d8(), iVar8 == 0)) {
              return;
            }
            iVar11 = iVar11 + 1;
          } while (iVar11 < iVar12);
        }
        sVar6 = 0;
        iVar11 = 0;
        sVar13 = 0;
        iVar12 = 0;
        do {
          iVar9 = sVar6 * 6;
          iVar7 = 0;
          iVar8 = iVar12;
          do {
            puVar5 = PTR_DAT_00012d6c;
            uVar3 = PTR_DAT_00012d6c[iVar8];
            iVar10 = FUN_000034d8(uVar3);
            if (iVar10 != 0) {
              *(short *)((int)&local_1a0 + iVar9) = sVar13 + (short)iVar7;
              uVar2 = puVar5[iVar8 + 2];
              sVar6 = sVar6 + 1;
              local_19e[iVar9 + 1] = uVar3;
              local_19e[iVar9] = uVar2;
              local_19e[iVar9 + 2] = puVar5[iVar8 + 1];
              iVar9 = iVar9 + 6;
            }
            iVar7 = iVar7 + 1;
            iVar8 = iVar8 + 0x14;
          } while (iVar7 < 0xf);
          iVar11 = iVar11 + 1;
          iVar12 = iVar12 + 300;
          sVar13 = sVar13 + 0xf;
        } while (iVar11 < 0x13);
        iVar12 = 0;
        _qsort(&local_1a0,sVar6,6,(int *)PTR_LAB_00008108);
        iVar11 = 0;
        do {
          lVar14 = 0xe;
          iVar8 = iVar11;
          do {
            puVar5 = PTR_DAT_00012d6c;
            iVar9 = FUN_000034d8(PTR_DAT_00012d6c[iVar8]);
            if (iVar9 != 0) {
              puVar5[iVar8] = 0;
            }
            lVar14 = lVar14 + -1;
            iVar8 = iVar8 + 0x14;
          } while (-1 < lVar14);
          iVar12 = iVar12 + 1;
          iVar11 = iVar11 + 300;
        } while (iVar12 < 0x13);
        if (0 < (int)sVar6) {
          iVar12 = 0;
          do {
            iVar11 = FUN_000058fc(*param_1);
            iVar8 = FUN_000058fc(param_1[1]);
            iVar8 = iVar11 * 0x34 + iVar8;
            uVar3 = local_19e[iVar12 + 1];
            sVar6 = sVar6 - 1;
            param_1 = param_1 + 2;
            lVar14 = (longlong)(iVar8 / 0x11d + (iVar8 >> 0x1f)) - (longlong)(iVar8 >> 0x1f);
            local_19e[iVar12] = (char)lVar14;
            *(short *)((int)&local_1a0 + iVar12) = (short)iVar8 + (short)lVar14 * -0x11d;
            iVar11 = (uint)*(ushort *)((int)&local_1a0 + iVar12) * 0x14;
            puVar5[iVar11 + 2] = local_19e[iVar12];
            uVar4 = *(ushort *)((int)&local_1a0 + iVar12);
            uVar2 = local_19e[iVar12 + 2];
            puVar5[iVar11] = uVar3;
            puVar5[(uint)uVar4 * 0x14 + 1] = uVar2;
            iVar12 = iVar12 + 6;
          } while (sVar6 != 0);
        }
        FUN_00004f14();
      }
    }
  }
  return;
}



// Function: FUN_00005e64 @ 0x00005e64

undefined8 FUN_00005e64(int param_1)

{
  bool bVar1;
  
  if (param_1 == 0x2d) {
    FUN_00005858();
    return 0;
  }
  if (param_1 < 0x2e) {
    if (param_1 == 0x20) goto LAB_00005ef0;
    if (param_1 < 0x21) {
      if (param_1 != 0x1b) {
        return 0;
      }
      return 1;
    }
    bVar1 = param_1 == 0x2b;
  }
  else {
    if (param_1 == 0x4c) {
      *(undefined4 *)PTR_DAT_00012d48 = 1;
      FUN_00004494();
      return 0;
    }
    if (0x4c < param_1) {
      if (param_1 != 0x72) {
        return 0;
      }
      FUN_00005668(0);
      return 0;
    }
    bVar1 = param_1 == 0x3d;
  }
  if (!bVar1) {
    return 0;
  }
LAB_00005ef0:
  if (*(int *)(PTR_DAT_00012d54 + DAT_0000803c * 4 + 4) != 0) {
    FUN_00005800();
  }
  return 0;
}



// Function: FUN_00005f38 @ 0x00005f38

void FUN_00005f38(void)

{
  FUN_00004138();
  FUN_000068e8();
  DAT_00012dd0 = 0x280;
  DAT_00012dd4 = 0x1e0;
  DAT_00012dcc = _malloc(0xe1000);
  *(uint *)PTR_DAT_00012d28 = (uint)(byte)*PTR_DAT_00012d20;
  FUN_00005668(1);
  return;
}



// Function: FUN_00006048 @ 0x00006048

void FUN_00006048(undefined8 param_1,longlong param_2,longlong param_3,undefined8 param_4)

{
  ulonglong uVar1;
  undefined8 uVar2;
  char *pcVar3;
  
  uVar1 = FUN_000045d4();
  if ((longlong)uVar1 < 0) {
    return;
  }
  if ((int)uVar1 == -1) {
    pcVar3 = "b != -1";
    uVar2 = 0xa5c;
  }
  else {
    if ((int)uVar1 < *(int *)PTR_DAT_00012d1c) {
      FUN_000047e0(param_2 + -0xc,param_3 + -0xc,
                   *(undefined4 *)(PTR_DAT_00012d34 + (int)((uVar1 & 0xffffffff) << 2)),0x18,0x18,
                   0x18,param_4,0);
      return;
    }
    pcVar3 = "b < num_images";
    uVar2 = 0xa5d;
  }
                    /* WARNING: Subroutine does not return */
  FUN_00006ac0("%s:%u: failed assertion `%s\'\n","../game.c",uVar2,pcVar3);
}



// Function: FUN_00006128 @ 0x00006128

void FUN_00006128(longlong param_1,longlong param_2,undefined8 param_3)

{
  longlong lVar1;
  int iVar3;
  ulonglong uVar2;
  longlong lVar4;
  
  iVar3 = (int)param_1;
  if ((int)param_2 < 0xf) {
    lVar4 = param_2 * 0x18 + 0x1e;
    lVar1 = param_1 * 0x18 + 0x3c;
  }
  else {
    lVar1 = ((longlong)iVar3 / 6 + ((longlong)iVar3 >> 0x3f) & 0xffffffffU) -
            (longlong)(iVar3 >> 0x1f);
    lVar4 = lVar1 * 0x1a + 0x14;
    lVar1 = (param_1 + lVar1 * -6) * 0x1a + 0x1cc;
  }
  if (((DAT_00012db0 == 2) && (iVar3 == *(int *)PTR_DAT_00012d30)) &&
     ((int)param_2 == *(int *)PTR_DAT_00012d2c)) {
    uVar2 = ZEXT48(&DAT_00012db4);
  }
  else {
    uVar2 = param_2 * 300 + param_1 * 0x14 + ZEXT48(PTR_DAT_00012d6c);
  }
  FUN_00006048(uVar2,lVar1,lVar4,param_3);
  return;
}



// Function: FUN_000061ec @ 0x000061ec

undefined8 FUN_000061ec(int param_1,int param_2)

{
  byte bVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  undefined8 uVar7;
  uint uVar8;
  uint uVar9;
  int iVar10;
  int iVar11;
  int local_40 [16];
  
  iVar2 = param_1 * 0x18;
  iVar6 = param_2 * 0x18;
  iVar11 = iVar2 + 0x3c;
  iVar10 = iVar6 + 0x1e;
  uVar8 = 0;
  _memset(local_40,0,0x10);
  uVar7 = 0;
  uVar9 = 0;
  do {
    iVar3 = param_2 * 300 + param_1 * 0x14;
    if ((PTR_DAT_00012d6c[uVar9 + iVar3 + 0xc] | PTR_DAT_00012d6c[(uVar9 + 4 & 7) + iVar3 + 4]) == 0
       ) goto LAB_00006388;
    uVar7 = 1;
    iVar4 = iVar11;
    iVar5 = iVar10;
    switch(uVar9) {
    case 0:
      break;
    case 1:
      iVar4 = iVar2 + 0x49;
      break;
    case 2:
      iVar4 = iVar2 + 0x49;
      goto LAB_00006354;
    case 3:
      iVar4 = iVar2 + 0x49;
      goto LAB_00006318;
    case 4:
      goto LAB_00006318;
    case 5:
      iVar4 = iVar2 + 0x2f;
LAB_00006318:
      iVar5 = iVar6 + 0x2b;
      goto LAB_00006354;
    case 6:
      iVar4 = iVar2 + 0x2f;
      goto LAB_00006354;
    case 7:
      iVar4 = iVar2 + 0x2f;
      break;
    default:
      goto switchD_000062a8_default;
    }
    iVar5 = iVar6 + 0x11;
LAB_00006354:
    FUN_00004b28(*(undefined4 *)
                  (&DAT_000080d4 +
                  (uint)(byte)(PTR_DAT_00012d6c[uVar9 + iVar3 + 0xc] |
                              PTR_DAT_00012d6c[(uVar9 + 4 & 7) + iVar3 + 4]) * 4),iVar11,iVar10,
                 iVar4,iVar5);
switchD_000062a8_default:
    iVar3 = uVar9 + param_2 * 300 + param_1 * 0x14;
    bVar1 = PTR_DAT_00012d6c[iVar3 + 4];
    if (bVar1 == PTR_DAT_00012d6c[iVar3 + 0xc]) {
      local_40[uVar9 & 3] = 1;
      uVar8 = uVar8 | bVar1;
    }
LAB_00006388:
    uVar9 = uVar9 + 1;
    if (7 < (int)uVar9) {
      if ((uVar8 != 0) && (1 < local_40[0] + local_40[1] + local_40[2] + local_40[3])) {
        FUN_00004b28(*(undefined4 *)(&DAT_000080d4 + uVar8 * 4),iVar11,iVar10,iVar11,iVar10);
      }
      return uVar7;
    }
  } while( true );
}



// Function: FUN_000063fc @ 0x000063fc

void FUN_000063fc(longlong param_1,undefined8 param_2,char *param_3,undefined8 param_4)

{
  char cVar1;
  
  cVar1 = *param_3;
  while (cVar1 != '\0') {
    if ((int)cVar1 - 0x30U < 10) {
      FUN_000047e0(param_1,param_2,
                   *(undefined4 *)(PTR_DAT_00012d34 + ((int)cVar1 - 0x30U) * 4 + 0x1d8),0xc,0xc,0x18
                   ,0xe,param_4);
      param_1 = param_1 + 8;
    }
    else {
      param_1 = param_1 + 4;
    }
    param_3 = param_3 + 1;
    cVar1 = *param_3;
  }
  return;
}



// Function: FUN_000064a0 @ 0x000064a0

undefined8 FUN_000064a0(int param_1)

{
  if (param_1 == DAT_0000803c) {
    return 0;
  }
  if (*(int *)(PTR_DAT_00012d58 + param_1 * 4) != 0) {
    return 0x48;
  }
  if (*(int *)(PTR_DAT_00012d54 + param_1 * 4) != 0) {
    return 0x30;
  }
  return 0x10;
}



// Function: FUN_000065d0 @ 0x000065d0

/* WARNING: Restarted to delay deadcode elimination for space: stack */

void FUN_000065d0(void)

{
  char cVar1;
  undefined8 uVar2;
  int iVar3;
  longlong lVar4;
  longlong lVar5;
  longlong lVar6;
  char local_20;
  char local_1f;
  undefined1 local_1e;
  
  lVar4 = 0;
  _memset(DAT_00012dcc,0xa4,DAT_00012dd0 * DAT_00012dd4 * 3);
  do {
    lVar6 = 0;
    do {
      lVar5 = lVar6 + 1;
      FUN_00006128(lVar6,lVar4,0);
      lVar6 = lVar5;
    } while ((int)lVar5 < 0xf);
    lVar4 = lVar4 + 1;
  } while ((int)lVar4 < 0xf);
  lVar4 = 0;
  do {
    lVar6 = 0;
    do {
      iVar3 = FUN_000061ec(lVar6,lVar4);
      if (iVar3 != 0) {
        FUN_00006128(lVar6,lVar4,0x10);
      }
      lVar6 = lVar6 + 1;
    } while ((int)lVar6 < 0xf);
    lVar4 = lVar4 + 1;
  } while ((int)lVar4 < 0xf);
  lVar4 = 0;
  do {
    lVar6 = lVar4 + 1;
    FUN_00006128(lVar4,0xf,0);
    lVar4 = lVar6;
  } while ((int)lVar6 < 0x18);
  if (*(int *)PTR_DAT_00012d44 == 2) {
    lVar4 = 1;
    do {
      lVar5 = lVar4 + -1;
      uVar2 = FUN_000064a0(lVar5);
      iVar3 = (int)lVar5 >> 0x1f;
      cVar1 = (char)((int)lVar4 / 10);
      local_20 = cVar1 + '0';
      lVar6 = (longlong)((int)lVar5 / 0x19 + iVar3);
      local_1f = (char)lVar4 + cVar1 * -10 + '0';
      local_1e = 0;
      if (local_20 == '0') {
        local_20 = ' ';
      }
      lVar4 = lVar4 + 1;
      FUN_000063fc((lVar5 + (lVar6 - iVar3) * -0x19) * 0x14 + 10,(lVar6 - iVar3) * 0x14 + 0x19a,
                   &local_20,uVar2);
    } while ((int)lVar4 < 0x33);
    return;
  }
  return;
}



// Function: FUN_000066e0 @ 0x000066e0

void FUN_000066e0(void)

{
  byte bVar1;
  byte bVar2;
  undefined *puVar3;
  char *pcVar4;
  undefined8 uVar5;
  byte *pbVar6;
  byte bVar7;
  byte *pbVar8;
  
  if (*PTR_DAT_00012d18 == '\0') {
    pbVar8 = &DAT_000080f4;
    pbVar6 = PTR_DAT_00012d18;
    bVar7 = 0;
    do {
      bVar1 = *pbVar8;
      pbVar8 = pbVar8 + 1;
      *pbVar6 = bVar1 ^ bVar7;
      bVar2 = *pbVar6;
      pbVar6 = pbVar6 + 1;
      bVar7 = bVar1;
    } while (bVar2 != 0);
  }
  if (DAT_00008040 != 0) {
    FUN_000065d0();
  }
  FUN_00004e68();
  if (*(int *)PTR_DAT_00012d4c == 0) {
    if (*(int *)(PTR_DAT_00012d58 + DAT_0000803c * 4) == 0) goto LAB_000067c8;
    uVar5 = 0x15e;
    pcVar4 = "(won)";
  }
  else {
    uVar5 = 0x14a;
    pcVar4 = "You win!";
  }
  FUN_00003228(pcVar4,uVar5,0x181,400,0x1a4);
LAB_000067c8:
  puVar3 = PTR_DAT_00012d44;
  if (*(int *)PTR_DAT_00012d44 != 2) {
    FUN_00003228(PTR_DAT_00012d14,0x15e,0x1a4,0x1c2,0x1cc);
  }
  pcVar4 = PTR_DAT_00012d10;
  if ((*(int *)puVar3 == 2) && (*(int *)PTR_DAT_00012d4c != 0)) {
    pcVar4 = "Click on a level or press spacebar for next.";
  }
  FUN_00003228(pcVar4,0x1c2,0x7d,0x26c,0x1db);
  FUN_00003228("freeware",0,0x1c2,100,0x1e0);
  if ((0x27 < (int)DAT_0000803c) && (((DAT_0000803c & 1) == 0 || (DAT_0000803c == 0x31)))) {
    FUN_00003228("more levels @",0x15e,0x1c2,0x1d1,0x1e0);
  }
  FUN_00003228(PTR_DAT_00012d18,0x1d6,0x1c2,0x280,0x1e0);
  return;
}



// Function: FUN_000068c0 @ 0x000068c0

void FUN_000068c0(void)

{
  FUN_000055f4();
  FUN_0000433c();
  return;
}



// Function: FUN_000068e8 @ 0x000068e8

void FUN_000068e8(void)

{
  bool bVar1;
  byte bVar2;
  int iVar3;
  undefined *puVar4;
  undefined *puVar5;
  uint *puVar6;
  void *pvVar7;
  uint uVar8;
  int iVar9;
  ulonglong uVar10;
  byte *pbVar11;
  byte *pbVar12;
  longlong lVar13;
  undefined1 local_30;
  undefined1 uStack_2f;
  undefined1 uStack_2e;
  
  uVar10 = (ulonglong)*(uint *)PTR_DAT_00012d1c - 1;
  if (-1 < (longlong)uVar10) {
    lVar13 = (uVar10 & 0x3fffffff) << 2;
    do {
      puVar4 = PTR_DAT_00012d34;
      iVar3 = (int)lVar13;
      pbVar11 = *(byte **)(PTR_PTR_00012d80 + iVar3);
      pvVar7 = _malloc(0x240);
      iVar9 = 0;
      *(void **)(puVar4 + iVar3) = pvVar7;
      bVar1 = false;
      do {
        puVar5 = PTR_DAT_00012d34;
        bVar2 = *pbVar11;
        uVar8 = (uint)bVar2;
        pbVar12 = pbVar11 + 1;
        if (bVar2 < 0xc1) {
          *(byte *)(*(int *)(puVar4 + iVar3) + iVar9) = bVar2;
          iVar9 = iVar9 + 1;
        }
        else {
          if (!bVar1) {
            do {
              uVar8 = uVar8 - 1;
              *(byte *)(*(int *)(puVar5 + iVar3) + iVar9) = *pbVar12;
              iVar9 = iVar9 + 1;
              if ((int)uVar8 < 0xc1) break;
            } while (iVar9 < 0x240);
          }
          pbVar12 = pbVar11 + 2;
        }
        bVar1 = 0x23f < iVar9;
        pbVar11 = pbVar12;
      } while (!bVar1);
      uVar10 = uVar10 - 1;
      lVar13 = lVar13 + -4;
    } while (-1 < (longlong)uVar10);
  }
  lVar13 = 0x100;
  puVar6 = (uint *)PTR_DAT_00012d40;
  do {
    uVar8 = *puVar6 & 0xffffff00;
    uStack_2e = (undefined1)(uVar8 >> 8);
    *(undefined1 *)puVar6 = uStack_2e;
    uStack_2f = (undefined1)(uVar8 >> 0x10);
    *(undefined1 *)((int)puVar6 + 1) = uStack_2f;
    local_30 = (undefined1)(uVar8 >> 0x18);
    *(undefined1 *)((int)puVar6 + 2) = local_30;
    puVar6 = (uint *)((int)puVar6 + 3);
    lVar13 = lVar13 + -1;
  } while (lVar13 != 0);
  return;
}



// Function: FUN_000069fc @ 0x000069fc

undefined * FUN_000069fc(void)

{
  char cVar1;
  char cVar2;
  char cVar3;
  char *pcVar4;
  undefined *puVar5;
  int iVar6;
  undefined *puVar7;
  
  pcVar4 = *(char **)(PTR_DAT_00012d7c + *(int *)PTR_DAT_00012d28 * 4);
  _strcpy(PTR_DAT_00012d10,*(char **)(PTR_DAT_00012d78 + *(int *)PTR_DAT_00012d28 * 4));
  puVar5 = PTR_DAT_00012d6c;
  puVar7 = _memset(PTR_DAT_00012d6c,0,0x13ec);
  cVar1 = *pcVar4;
  while (cVar1 != '\0') {
    cVar2 = pcVar4[1];
    cVar3 = pcVar4[2];
    iVar6 = (uint)(byte)pcVar4[4] * 300 + (uint)(byte)pcVar4[3] * 0x14;
    puVar5[iVar6] = cVar1;
    puVar5[iVar6 + 1] = cVar3;
    puVar5[iVar6 + 2] = cVar2;
    pcVar4 = pcVar4 + 5;
    puVar7 = puVar5;
    cVar1 = *pcVar4;
  }
  return puVar7;
}



// Function: FUN_00006ac0 @ 0x00006ac0

void FUN_00006ac0(char *param_1,undefined8 param_2,undefined8 param_3,undefined8 param_4)

{
  undefined *puVar1;
  
  puVar1 = PTR_00012d84;
  _fprintf((FILE *)(PTR_00012d84 + 0xb0),param_1,param_2,param_3,param_4);
  _fflush((FILE *)(puVar1 + 0xb0));
                    /* WARNING: Subroutine does not return */
  _abort();
}



// Function: _exit @ 0x00006b0c

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void _exit(int param_1)

{
                    /* WARNING: Could not recover jumptable at 0x00006b2c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012be0)(param_1);
  return;
}



// Function: _atexit @ 0x00006b30

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

int _atexit(void *param_1)

{
  int iVar1;
  
                    /* WARNING: Could not recover jumptable at 0x00006b50. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  iVar1 = (*(code *)PTR_LAB_00012be4)(param_1);
  return iVar1;
}



// Function: ___keymgr_dwarf2_register_sections @ 0x00006b54

void ___keymgr_dwarf2_register_sections(void)

{
                    /* WARNING: Could not recover jumptable at 0x00006b74. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012be8)();
  return;
}



// Function: __dyld_register_func_for_remove_image @ 0x00007790

void __dyld_register_func_for_remove_image(void)

{
                    /* WARNING: Could not recover jumptable at 0x000077ac. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012bec)();
  return;
}



// Function: __dyld_register_func_for_add_image @ 0x000077b0

void __dyld_register_func_for_add_image(void)

{
                    /* WARNING: Could not recover jumptable at 0x000077cc. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012bf0)();
  return;
}



// Function: __init_keymgr @ 0x000077d0

void __init_keymgr(void)

{
                    /* WARNING: Could not recover jumptable at 0x000077ec. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012bf4)();
  return;
}



// Function: _free @ 0x000077f0

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void _free(void *param_1)

{
                    /* WARNING: Could not recover jumptable at 0x0000780c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012bf8)(param_1);
  return;
}



// Function: _abort @ 0x00007810

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void _abort(void)

{
                    /* WARNING: Could not recover jumptable at 0x0000782c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012bfc)();
  return;
}



// Function: __keymgr_set_and_unlock_processwide_ptr @ 0x00007830

void __keymgr_set_and_unlock_processwide_ptr(void)

{
                    /* WARNING: Could not recover jumptable at 0x0000784c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c00)();
  return;
}



// Function: __keymgr_get_and_lock_processwide_ptr @ 0x00007850

void __keymgr_get_and_lock_processwide_ptr(void)

{
                    /* WARNING: Could not recover jumptable at 0x0000786c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c04)();
  return;
}



// Function: _calloc @ 0x00007870

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void * _calloc(size_t param_1,size_t param_2)

{
  void *pvVar1;
  
                    /* WARNING: Could not recover jumptable at 0x0000788c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  pvVar1 = (void *)(*(code *)PTR_LAB_00012c08)(param_1,param_2);
  return pvVar1;
}



// Function: _IsWindowHilited @ 0x00007890

void _IsWindowHilited(void)

{
                    /* WARNING: Could not recover jumptable at 0x000078ac. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c0c)();
  return;
}



// Function: _PtInRect @ 0x000078b0

void _PtInRect(void)

{
                    /* WARNING: Could not recover jumptable at 0x000078cc. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c10)();
  return;
}



// Function: _GetWindowBounds @ 0x000078d0

void _GetWindowBounds(void)

{
                    /* WARNING: Could not recover jumptable at 0x000078ec. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c14)();
  return;
}



// Function: _GetEventKind @ 0x000078f0

void _GetEventKind(void)

{
                    /* WARNING: Could not recover jumptable at 0x0000790c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c18)();
  return;
}



// Function: _CFRelease @ 0x00007910

void _CFRelease(void)

{
                    /* WARNING: Could not recover jumptable at 0x0000792c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c1c)();
  return;
}



// Function: _DrawThemeTextBox @ 0x00007930

void _DrawThemeTextBox(void)

{
                    /* WARNING: Could not recover jumptable at 0x0000794c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c20)();
  return;
}



// Function: _CFStringCreateWithCString @ 0x00007950

void _CFStringCreateWithCString(void)

{
                    /* WARNING: Could not recover jumptable at 0x0000796c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c24)();
  return;
}



// Function: _CGDataProviderRelease @ 0x00007970

void _CGDataProviderRelease(void)

{
                    /* WARNING: Could not recover jumptable at 0x0000798c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c28)();
  return;
}



// Function: _CGImageRelease @ 0x00007990

void _CGImageRelease(void)

{
                    /* WARNING: Could not recover jumptable at 0x000079ac. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c2c)();
  return;
}



// Function: _CGContextDrawImage @ 0x000079b0

void _CGContextDrawImage(void)

{
                    /* WARNING: Could not recover jumptable at 0x000079cc. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c30)();
  return;
}



// Function: _CGImageCreate @ 0x000079d0

void _CGImageCreate(void)

{
                    /* WARNING: Could not recover jumptable at 0x000079ec. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c34)();
  return;
}



// Function: _CGColorSpaceCreateDeviceRGB @ 0x000079f0

void _CGColorSpaceCreateDeviceRGB(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007a0c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c38)();
  return;
}



// Function: _CGDataProviderCreateWithData @ 0x00007a10

void _CGDataProviderCreateWithData(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007a2c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c3c)();
  return;
}



// Function: _GetScrapFlavorData @ 0x00007a30

void _GetScrapFlavorData(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007a4c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c40)();
  return;
}



// Function: _GetScrapFlavorSize @ 0x00007a50

void _GetScrapFlavorSize(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007a6c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c44)();
  return;
}



// Function: _PutScrapFlavor @ 0x00007a70

void _PutScrapFlavor(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007a8c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c48)();
  return;
}



// Function: _strlen @ 0x00007a90

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

size_t _strlen(char *param_1)

{
  size_t sVar1;
  
                    /* WARNING: Could not recover jumptable at 0x00007aac. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  sVar1 = (*(code *)PTR_LAB_00012c4c)(param_1);
  return sVar1;
}



// Function: _GetCurrentScrap @ 0x00007ab0

void _GetCurrentScrap(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007acc. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c50)();
  return;
}



// Function: _ClearCurrentScrap @ 0x00007ad0

void _ClearCurrentScrap(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007aec. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c54)();
  return;
}



// Function: _QDEndCGContext @ 0x00007af0

void _QDEndCGContext(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007b0c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c58)();
  return;
}



// Function: _CGContextFlush @ 0x00007b10

void _CGContextFlush(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007b2c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c5c)();
  return;
}



// Function: _QDBeginCGContext @ 0x00007b30

void _QDBeginCGContext(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007b4c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c60)();
  return;
}



// Function: _GetWindowPort @ 0x00007b50

void _GetWindowPort(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007b6c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c64)();
  return;
}



// Function: _QuitApplicationEventLoop @ 0x00007b70

void _QuitApplicationEventLoop(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007b8c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c68)();
  return;
}



// Function: _GetEventParameter @ 0x00007b90

void _GetEventParameter(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007bac. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c6c)();
  return;
}



// Function: _InvalWindowRect @ 0x00007bb0

void _InvalWindowRect(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007bcc. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c70)();
  return;
}



// Function: _CFPreferencesAppSynchronize @ 0x00007bd0

void _CFPreferencesAppSynchronize(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007bec. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c74)();
  return;
}



// Function: _RunApplicationEventLoop @ 0x00007bf0

void _RunApplicationEventLoop(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007c0c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c78)();
  return;
}



// Function: _ShowWindow @ 0x00007c10

void _ShowWindow(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007c2c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c7c)();
  return;
}



// Function: _RepositionWindow @ 0x00007c30

void _RepositionWindow(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007c4c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c80)();
  return;
}



// Function: _chdir @ 0x00007c50

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

int _chdir(char *param_1)

{
  int iVar1;
  
                    /* WARNING: Could not recover jumptable at 0x00007c6c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  iVar1 = (*(code *)PTR_LAB_00012c84)(param_1);
  return iVar1;
}



// Function: _FSRefMakePath @ 0x00007c70

void _FSRefMakePath(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007c8c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c88)();
  return;
}



// Function: _FSFindFolder @ 0x00007c90

void _FSFindFolder(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007cac. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c8c)();
  return;
}



// Function: _SetWindowTitleWithCFString @ 0x00007cb0

void _SetWindowTitleWithCFString(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007ccc. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c90)();
  return;
}



// Function: _CreateNewWindow @ 0x00007cd0

void _CreateNewWindow(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007cec. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c94)();
  return;
}



// Function: _CFPreferencesSetAppValue @ 0x00007cf0

void _CFPreferencesSetAppValue(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007d0c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c98)();
  return;
}



// Function: _SetMenuCommandMark @ 0x00007d10

void _SetMenuCommandMark(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007d2c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012c9c)();
  return;
}



// Function: _GetMenuCommandMark @ 0x00007d30

void _GetMenuCommandMark(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007d4c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012ca0)();
  return;
}



// Function: _CFPreferencesGetAppBooleanValue @ 0x00007d50

void _CFPreferencesGetAppBooleanValue(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007d6c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012ca4)();
  return;
}



// Function: _DisposeNibReference @ 0x00007d70

void _DisposeNibReference(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007d8c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012ca8)();
  return;
}



// Function: _SetMenuBarFromNib @ 0x00007d90

void _SetMenuBarFromNib(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007dac. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012cac)();
  return;
}



// Function: _CreateNibReference @ 0x00007db0

void _CreateNibReference(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007dcc. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012cb0)();
  return;
}



// Function: ___CFStringMakeConstantString @ 0x00007dd0

void ___CFStringMakeConstantString(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007dec. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012cb4)();
  return;
}



// Function: _InstallEventHandler @ 0x00007df0

void _InstallEventHandler(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007e0c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012cb8)();
  return;
}



// Function: _NewEventHandlerUPP @ 0x00007e10

void _NewEventHandlerUPP(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007e2c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012cbc)();
  return;
}



// Function: _GetWindowEventTarget @ 0x00007e30

void _GetWindowEventTarget(void)

{
                    /* WARNING: Could not recover jumptable at 0x00007e4c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012cc0)();
  return;
}



// Function: _qsort @ 0x00007e50

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void _qsort(void *param_1,size_t param_2,size_t param_3,int *param_4)

{
                    /* WARNING: Could not recover jumptable at 0x00007e6c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  (*(code *)PTR_LAB_00012cc4)(param_1,param_2,param_3,param_4);
  return;
}



// Function: _memcpy @ 0x00007e70

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void * _memcpy(void *param_1,void *param_2,size_t param_3)

{
  void *pvVar1;
  
                    /* WARNING: Could not recover jumptable at 0x00007e8c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  pvVar1 = (void *)(*(code *)PTR_LAB_00012cc8)(param_1,param_2,param_3);
  return pvVar1;
}



// Function: _fwrite @ 0x00007e90

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

size_t _fwrite(void *param_1,size_t param_2,size_t param_3,FILE *param_4)

{
  size_t sVar1;
  
                    /* WARNING: Could not recover jumptable at 0x00007eac. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  sVar1 = (*(code *)PTR_LAB_00012ccc)(param_1,param_2,param_3,param_4);
  return sVar1;
}



// Function: _fclose @ 0x00007eb0

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

int _fclose(FILE *param_1)

{
  int iVar1;
  
                    /* WARNING: Could not recover jumptable at 0x00007ecc. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  iVar1 = (*(code *)PTR_LAB_00012cd0)(param_1);
  return iVar1;
}



// Function: _memset @ 0x00007ed0

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void * _memset(void *param_1,int param_2,size_t param_3)

{
  void *pvVar1;
  
                    /* WARNING: Could not recover jumptable at 0x00007eec. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  pvVar1 = (void *)(*(code *)PTR_LAB_00012cd4)(param_1,param_2,param_3);
  return pvVar1;
}



// Function: _malloc @ 0x00007ef0

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

void * _malloc(size_t param_1)

{
  void *pvVar1;
  
                    /* WARNING: Could not recover jumptable at 0x00007f0c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  pvVar1 = (void *)(*(code *)PTR_LAB_00012cd8)(param_1);
  return pvVar1;
}



// Function: _fread @ 0x00007f10

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

size_t _fread(void *param_1,size_t param_2,size_t param_3,FILE *param_4)

{
  size_t sVar1;
  
                    /* WARNING: Could not recover jumptable at 0x00007f2c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  sVar1 = (*(code *)PTR_LAB_00012cdc)(param_1,param_2,param_3,param_4);
  return sVar1;
}



// Function: _fopen @ 0x00007f30

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

FILE * _fopen(char *param_1,char *param_2)

{
  FILE *pFVar1;
  
                    /* WARNING: Could not recover jumptable at 0x00007f4c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  pFVar1 = (FILE *)(*(code *)PTR_LAB_00012ce0)(param_1,param_2);
  return pFVar1;
}



// Function: _strcpy @ 0x00007f50

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

char * _strcpy(char *param_1,char *param_2)

{
  char *pcVar1;
  
                    /* WARNING: Could not recover jumptable at 0x00007f6c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  pcVar1 = (char *)(*(code *)PTR_LAB_00012ce4)(param_1,param_2);
  return pcVar1;
}



// Function: _fflush @ 0x00007f70

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

int _fflush(FILE *param_1)

{
  int iVar1;
  
                    /* WARNING: Could not recover jumptable at 0x00007f8c. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  iVar1 = (*(code *)PTR_LAB_00012ce8)(param_1);
  return iVar1;
}



// Function: _fprintf @ 0x00007f90

/* WARNING: Unknown calling convention -- yet parameter storage is locked */

int _fprintf(FILE *param_1,char *param_2,...)

{
  int iVar1;
  
                    /* WARNING: Could not recover jumptable at 0x00007fac. Too many branches */
                    /* WARNING: Treating indirect jump as call */
  iVar1 = (*(code *)PTR_LAB_00012cec)(param_1,param_2);
  return iVar1;
}



