# /// script
# requires-python = ">=3.13"
# dependencies = ["freetype-py", "Pillow"]
# ///
"""Extract bitmap glyph data from sserife.fon and generate Rust source code.

Reads Wine's MS Sans Serif bitmap font (sserife.fon, face 0 = 13px/8pt@96DPI),
extracts 1-bit bitmap data + metrics for ASCII 32-126, outputs:
  1. src/ms_sans_serif.rs — const glyph data for Rust bitmap font renderer
  2. scripts/sserife_glyphs.png — visual sprite sheet for manual inspection
"""
import freetype
from PIL import Image

FON_PATH = "assets/fonts/sserife.fon"
RUST_OUTPUT = "src/ms_sans_serif.rs"
PNG_OUTPUT = "scripts/sserife_glyphs.png"

# Load face 0 = 13px height (8pt at 96 DPI)
face = freetype.Face(FON_PATH, 0)
face.select_size(0)
face.set_charmap(face.charmaps[0])

# Get font-level metrics
ascender = face.size.ascender >> 6   # 26.6 fixed point → pixels
descender = face.size.descender >> 6
height = face.size.height >> 6

print(f"Font metrics: ascender={ascender}, descender={descender}, height={height}")

# Extract glyphs for ASCII 32-126
glyphs = []
for code in range(32, 127):
    face.load_char(chr(code), freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO)
    bitmap = face.glyph.bitmap
    advance = face.glyph.advance.x >> 6  # 26.6 fixed point
    bearing_x = face.glyph.bitmap_left
    bearing_y = face.glyph.bitmap_top
    bw = bitmap.width
    bh = bitmap.rows
    pitch = bitmap.pitch  # bytes per row (may have padding)

    # Extract 1-bit bitmap data, packed as bytes (MSB = leftmost pixel)
    # FreeType FT_PIXEL_MODE_MONO: each row is `pitch` bytes, bit 7 = leftmost pixel
    rows_data = []
    buf = bitmap.buffer
    for row in range(bh):
        row_bytes = []
        for col_byte in range(pitch):
            idx = row * pitch + col_byte
            row_bytes.append(buf[idx] if idx < len(buf) else 0)
        rows_data.append(row_bytes)

    glyphs.append({
        'code': code,
        'char': chr(code),
        'advance': advance,
        'bearing_x': bearing_x,
        'bearing_y': bearing_y,
        'width': bw,
        'height': bh,
        'pitch': pitch,
        'bitmap': rows_data,
    })

    if 32 <= code < 127:
        ch = chr(code) if code != 92 else '\\\\'
        print(f"  '{ch}' (U+{code:04X}): advance={advance}, bearing=({bearing_x},{bearing_y}), bitmap={bw}x{bh}")

# --- Generate Rust source ---
lines = []
lines.append("/// MS Sans Serif 8pt bitmap font data, extracted from Wine's sserife.fon (LGPL 2.1).")
lines.append("/// Face 0 = 13px height (8pt at 96 DPI). Generated by scripts/extract_fon_glyphs.py.")
lines.append("///")
lines.append("/// Source: Wine's sserife.fon — pixel-perfect match for original Win32 SYSTEM_FONT.")
lines.append("")
lines.append("/// Per-glyph metrics and bitmap data.")
lines.append("#[derive(Clone, Copy)]")
lines.append("pub struct GlyphData {")
lines.append("    /// Character advance width in pixels")
lines.append("    pub advance: u8,")
lines.append("    /// Horizontal bearing (offset from pen position to left edge of bitmap)")
lines.append("    pub bearing_x: i8,")
lines.append("    /// Vertical bearing (offset from baseline to top edge of bitmap)")
lines.append("    pub bearing_y: i8,")
lines.append("    /// Bitmap width in pixels")
lines.append("    pub width: u8,")
lines.append("    /// Bitmap height in pixels")
lines.append("    pub height: u8,")
lines.append("    /// Bitmap pitch (bytes per row)")
lines.append("    pub pitch: u8,")
lines.append("    /// Offset into BITMAP_DATA where this glyph's rows start")
lines.append("    pub bitmap_offset: u16,")
lines.append("}")
lines.append("")
lines.append("/// Font height (tmHeight) = 13px")
lines.append("pub const FONT_HEIGHT: i32 = 13;")
lines.append("")
lines.append(f"/// Font ascent (ascender) = {ascender}px")
lines.append(f"pub const FONT_ASCENT: i32 = {ascender};")
lines.append("")
lines.append("/// Line spacing (tmHeight + tmExternalLeading) = 16px")
lines.append("/// Source: DrawTextA uses this for line skip")
lines.append("pub const LINE_SPACING: i32 = 16;")
lines.append("")

# Build flat bitmap data array and glyph table
bitmap_data = []
glyph_entries = []

for g in glyphs:
    offset = len(bitmap_data)
    # Flatten all row bytes into the bitmap data array
    for row_bytes in g['bitmap']:
        bitmap_data.extend(row_bytes)

    ch = g['char']
    if ch == '\\':
        ch_display = "'\\\\'"
    elif ch == "'":
        ch_display = "'\\''"
    else:
        ch_display = f"'{ch}'"

    glyph_entries.append(
        f"    GlyphData {{ advance: {g['advance']:2}, bearing_x: {g['bearing_x']:2}, "
        f"bearing_y: {g['bearing_y']:2}, width: {g['width']:2}, height: {g['height']:2}, "
        f"pitch: {g['pitch']}, bitmap_offset: {offset:4} }}, // {g['code']:3} {ch_display}"
    )

# Write glyph table
lines.append("/// Glyph metrics for ASCII 32-126 (95 characters).")
lines.append("/// Index = char_code - 32.")
lines.append("#[rustfmt::skip]")
lines.append(f"pub const GLYPHS: [GlyphData; {len(glyphs)}] = [")
for entry in glyph_entries:
    lines.append(entry)
lines.append("];")
lines.append("")

# Write bitmap data as a flat byte array
lines.append("/// Packed 1-bit bitmap data for all glyphs.")
lines.append("/// Each row is `pitch` bytes, MSB = leftmost pixel.")
lines.append("#[rustfmt::skip]")
lines.append(f"pub const BITMAP_DATA: [u8; {len(bitmap_data)}] = [")

# Write 16 bytes per line for readability
for i in range(0, len(bitmap_data), 16):
    chunk = bitmap_data[i:i+16]
    hex_bytes = ", ".join(f"0x{b:02X}" for b in chunk)
    lines.append(f"    {hex_bytes},")

lines.append("];")
lines.append("")

rust_src = "\n".join(lines)
with open(RUST_OUTPUT, "w") as f:
    f.write(rust_src)
print(f"\nWrote {RUST_OUTPUT} ({len(rust_src)} bytes, {len(glyphs)} glyphs, {len(bitmap_data)} bitmap bytes)")

# --- Generate PNG sprite sheet for visual inspection ---
# Layout: 16 chars per row, each cell = max_advance x FONT_HEIGHT
max_advance = max(g['advance'] for g in glyphs)
cell_w = max_advance + 2  # 2px padding
cell_h = 16  # line spacing for visual clarity
cols = 16
rows_img = (len(glyphs) + cols - 1) // cols
img_w = cols * cell_w
img_h = rows_img * cell_h

img = Image.new('RGB', (img_w, img_h), (164, 164, 164))  # gray background like game
pixels = img.load()

for idx, g in enumerate(glyphs):
    col = idx % cols
    row = idx // cols
    base_x = col * cell_w
    base_y = row * cell_h

    # Glyph origin: pen position is at (base_x, base_y + FONT_ASCENT)
    # bearing_x shifts right, bearing_y shifts up from baseline
    gx = base_x + g['bearing_x']
    gy = base_y + ascender - g['bearing_y']

    for by in range(g['height']):
        for bx in range(g['width']):
            byte_idx = by * g['pitch'] + (bx >> 3)
            bit_idx = 7 - (bx & 7)
            if byte_idx < len(g['bitmap'][by]):
                if g['bitmap'][by][byte_idx] & (1 << bit_idx):
                    px = gx + bx
                    py = gy + by
                    if 0 <= px < img_w and 0 <= py < img_h:
                        pixels[px, py] = (0, 0, 0)

img.save(PNG_OUTPUT)
print(f"Wrote {PNG_OUTPUT} ({img_w}x{img_h})")
