"""Generate src/levels.rs from extracted_data.json.

Usage: uv run scripts/generate_levels_rs.py
"""

import json
import os

data_path = os.path.join(os.path.dirname(__file__), "..", "decompiled", "extracted_data.json")
output_path = os.path.join(os.path.dirname(__file__), "..", "src", "levels.rs")

with open(data_path) as f:
    data = json.load(f)

levels = data["levels"]
level_order = data["level_order"]
palette = data["palette"]
sprites_rle = data["sprites_rle"]

lines = []
lines.append("/// Level data extracted byte-for-byte from chromatron_unpacked.exe")
lines.append("/// Generated by scripts/generate_levels_rs.py from decompiled/extracted_data.json")
lines.append("")
lines.append("use crate::types::{LevelDef, LevelPiece};")
lines.append("")

# Level order mapping (level_number → data_index)
lines.append("/// Level order: maps game level number (0–49) to level data index.")
lines.append("/// Source: DAT_0040b168, extracted from binary")
lines.append(f"pub const LEVEL_ORDER: [u8; 50] = {level_order};")
lines.append("")

# Generate level definitions
lines.append(f"/// All {len(levels)} unique level definitions.")
lines.append("/// Source: level grid data at DAT_0040e65c pointers, text at DAT_0040e758 pointers")
lines.append("pub const LEVELS: &[LevelDef] = &[")

for i, level in enumerate(levels):
    text = level["text"].replace("\\", "\\\\").replace('"', '\\"')
    pieces = level["pieces"]
    lines.append(f"    // Level data index {i}: {len(pieces)} pieces")
    lines.append(f"    LevelDef {{")
    lines.append(f'        text: "{text}",')
    lines.append(f"        pieces: &[")
    for p in pieces:
        lines.append(f"            LevelPiece {{ piece_type: {p['type']}, rotation: {p['rotation']}, color: {p['color']}, x: {p['x']}, y: {p['y']} }},")
    lines.append(f"        ],")
    lines.append(f"    }},")

lines.append("];")
lines.append("")

# Palette data
lines.append("/// Color palette (256 × RGB).")
lines.append("/// Source: DAT_00415934, 256 entries × 3 bytes (R, G, B)")
lines.append("pub const PALETTE: [(u8, u8, u8); 256] = [")
for i in range(0, 256, 8):
    entries = []
    for j in range(i, min(i+8, 256)):
        r, g, b = palette[j]
        entries.append(f"({r},{g},{b})")
    lines.append(f"    {', '.join(entries)},")
lines.append("];")
lines.append("")

# Sprite RLE data
lines.append(f"/// RLE-compressed sprite data ({len(sprites_rle)} sprites, each decompresses to 24×24 bytes).")
lines.append("/// Source: sprite pointers at PTR_DAT_00415734, RLE format: <0xC1=literal, >=0xC1=run")
lines.append(f"pub const SPRITES_RLE: [&[u8]; {len(sprites_rle)}] = [")
for i, sprite in enumerate(sprites_rle):
    data_str = ", ".join(f"0x{b:02x}" for b in sprite)
    lines.append(f"    // Sprite {i}")
    lines.append(f"    &[{data_str}],")
lines.append("];")

with open(output_path, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"[*] Generated {output_path}")
print(f"    {len(levels)} levels, {len(sprites_rle)} sprites, 256 palette entries")
