# /// script
# requires-python = ">=3.13"
# dependencies = ["freetype-py", "Pillow", "numpy"]
# ///
"""Generate ms_sans_serif.rs from Windows System font (vgasys.fon).

All 95 ASCII glyphs come from the same font — complete, consistent coverage.
Glyphs are cropped from 16px to 13px (rows 3:16) to match game rendering.
"""
import numpy as np
from PIL import Image
import freetype
import json

SYS_FON = "assets/fonts/vgasys.fon"
WIDTHS_PATH = "scripts/final_widths.json"
RUST_OUTPUT = "src/ms_sans_serif.rs"
SPRITE_OUTPUT = "scripts/extracted_glyphs.png"

FONT_HEIGHT = 13
FONT_ASCENT = 11
LINE_SPACING = 16

# All characters use bearing_x=0.
# Freetype reports bitmap_left=0 for all vgasys.fon glyphs.
# The bitmap data already includes any leading blank columns for spacing.

# Load advance widths (native from vgasys.fon)
with open(WIDTHS_PATH) as f:
    advances = json.load(f)

# Load System font
face = freetype.Face(SYS_FON, 0)
face.select_size(0)
face.set_charmap(face.charmaps[0])

print("=== Loading vgasys.fon glyphs ===")

final_glyphs = []
for code in range(32, 127):
    ch = chr(code)
    adv = advances.get(ch, 8)

    face.load_char(ch, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO)
    bm = face.glyph.bitmap

    # Extract raw bitmap
    raw = np.zeros((bm.rows, bm.width), dtype=bool)
    for by in range(bm.rows):
        for bx in range(bm.width):
            if bm.buffer[by * bm.pitch + (bx >> 3)] & (1 << (7 - (bx & 7))):
                raw[by, bx] = True

    # Crop to 13px: rows [3:16]
    if raw.shape[0] >= 16:
        bitmap_2d = raw[3:16, :]
    elif raw.shape[0] > 13:
        bitmap_2d = raw[3:3+13, :] if raw.shape[0] >= 16 else raw[:13, :]
    else:
        # Pad to 13 if needed
        bitmap_2d = np.zeros((13, raw.shape[1]), dtype=bool)
        bitmap_2d[:raw.shape[0], :] = raw

    # bearing_x=0 for all: freetype bitmap_left=0, bitmap includes leading space
    bearing_x = 0

    width = bitmap_2d.shape[1]
    height = FONT_HEIGHT
    bearing_y = FONT_ASCENT
    pitch = (width + 7) // 8

    # Pack bitmap into 1-bit bytes (MSB = leftmost)
    packed = []
    for row in range(height):
        for byte_idx in range(pitch):
            byte_val = 0
            for bit in range(8):
                col = byte_idx * 8 + bit
                if col < width and row < bitmap_2d.shape[0] and col < bitmap_2d.shape[1]:
                    if bitmap_2d[row, col]:
                        byte_val |= (1 << (7 - bit))
            packed.append(byte_val)

    px_count = int(np.sum(bitmap_2d))
    final_glyphs.append({
        'code': code,
        'char': ch,
        'advance': adv,
        'bearing_x': bearing_x,
        'bearing_y': bearing_y,
        'width': width,
        'height': height,
        'pitch': pitch,
        'packed': packed,
        'pixels': px_count,
    })

    if code >= 33:  # skip space
        print(f"  {code:3d} '{ch}': {width}x{height}, adv={adv}, bx={bearing_x}, {px_count}px")

print(f"\nTotal: {len(final_glyphs)} glyphs")

# ---- Generate Rust source ----
print(f"\n=== Generating {RUST_OUTPUT} ===")

lines = []
lines.append("/// Windows System font (vgasys.fon) bitmap data.")
lines.append("/// The original Chromatron game uses SYSTEM_FONT (the DC default),")
lines.append("/// which on Windows 2000/XP at 96 DPI maps to the System font.")
lines.append("/// Glyphs extracted from Microsoft's vgasys.fon, cropped from 16px to 13px (rows 3:16).")
lines.append("/// Advance widths are native from the font file.")
lines.append("/// Generated by scripts/generate_from_system_font.py.")
lines.append("")
lines.append("#[derive(Clone, Copy)]")
lines.append("pub struct GlyphData {")
lines.append("    pub advance: u8,")
lines.append("    pub bearing_x: i8,")
lines.append("    pub bearing_y: i8,")
lines.append("    pub width: u8,")
lines.append("    pub height: u8,")
lines.append("    pub pitch: u8,")
lines.append("    pub bitmap_offset: u16,")
lines.append("}")
lines.append("")
lines.append(f"pub const FONT_HEIGHT: i32 = {FONT_HEIGHT};")
lines.append(f"pub const FONT_ASCENT: i32 = {FONT_ASCENT};")
lines.append(f"pub const LINE_SPACING: i32 = {LINE_SPACING};")
lines.append("")

bitmap_data = []
glyph_entries = []

for g in final_glyphs:
    offset = len(bitmap_data)
    bitmap_data.extend(g['packed'])

    ch = g['char']
    if ch == '\\':
        ch_display = "'\\\\'"
    elif ch == "'":
        ch_display = "'\\''"
    else:
        ch_display = f"'{ch}'"

    glyph_entries.append(
        f"    GlyphData {{ advance: {g['advance']:2}, bearing_x: {g['bearing_x']:2}, "
        f"bearing_y: {g['bearing_y']:2}, width: {g['width']:2}, height: {g['height']:2}, "
        f"pitch: {g['pitch']}, bitmap_offset: {offset:4} }}, // {g['code']:3} {ch_display}"
    )

lines.append(f"/// Glyph metrics for ASCII 32-126 ({len(final_glyphs)} glyphs).")
lines.append("/// Index = char_code - 32.")
lines.append("#[rustfmt::skip]")
lines.append(f"pub const GLYPHS: [GlyphData; {len(final_glyphs)}] = [")
for entry in glyph_entries:
    lines.append(entry)
lines.append("];")
lines.append("")

lines.append(f"/// Packed 1-bit bitmap data ({len(bitmap_data)} bytes).")
lines.append("#[rustfmt::skip]")
lines.append(f"pub const BITMAP_DATA: [u8; {len(bitmap_data)}] = [")
for i in range(0, len(bitmap_data), 16):
    chunk = bitmap_data[i:i+16]
    hex_bytes = ", ".join(f"0x{b:02X}" for b in chunk)
    lines.append(f"    {hex_bytes},")
lines.append("];")
lines.append("")

rust_src = "\n".join(lines)
with open(RUST_OUTPUT, "w") as f:
    f.write(rust_src)
print(f"Wrote {RUST_OUTPUT} ({len(rust_src)} bytes, {len(bitmap_data)} bitmap bytes)")

# ---- Generate debug sprite sheet ----
print(f"\n=== Generating {SPRITE_OUTPUT} ===")
cell_w = 14
cell_h = 16
cols = 16
rows_img = (len(final_glyphs) + cols - 1) // cols
img_w = cols * cell_w
img_h = rows_img * cell_h

img = Image.new('RGB', (img_w, img_h), (164, 164, 164))
pixels = img.load()

for idx, g in enumerate(final_glyphs):
    col_idx = idx % cols
    row_idx = idx // cols
    base_x = col_idx * cell_w
    base_y = row_idx * cell_h
    gx = base_x + g['bearing_x']
    gy = base_y

    for by in range(g['height']):
        for bx in range(g['width']):
            byte_idx = by * g['pitch'] + (bx >> 3)
            bit_idx = 7 - (bx & 7)
            if byte_idx < len(g['packed']) and (g['packed'][byte_idx] & (1 << bit_idx)):
                px = gx + bx
                py = gy + by
                if 0 <= px < img_w and 0 <= py < img_h:
                    pixels[px, py] = (0, 0, 0)

img.save(SPRITE_OUTPUT)
print(f"Wrote {SPRITE_OUTPUT} ({img_w}x{img_h})")
