"""Export decompiled C, function list, strings, and imports from a binary using PyGhidra.

Usage: uv run scripts/ghidra_export_all.py <binary_path> <output_dir>
"""

import sys
import os

if len(sys.argv) < 3:
    print("Usage: uv run scripts/ghidra_export_all.py <binary_path> <output_dir>")
    sys.exit(1)

binary_path = os.path.abspath(sys.argv[1])
output_dir = os.path.abspath(sys.argv[2])
os.makedirs(output_dir, exist_ok=True)

# Must set GHIDRA_INSTALL_DIR before importing pyghidra
ghidra_dir = os.environ.get("GHIDRA_INSTALL_DIR", "/opt/homebrew/Cellar/ghidra/12.0/libexec")
os.environ["GHIDRA_INSTALL_DIR"] = ghidra_dir

import pyghidra
pyghidra.start()

from ghidra.app.decompiler import DecompInterface  # type: ignore
from ghidra.util.task import ConsoleTaskMonitor  # type: ignore

print(f"[*] Opening program: {binary_path}")
with pyghidra.open_program(binary_path) as flat_api:
    program = flat_api.getCurrentProgram()
    listing = program.getListing()
    func_manager = program.getFunctionManager()
    monitor = ConsoleTaskMonitor()

    # Set up decompiler
    decomp = DecompInterface()
    decomp.openProgram(program)

    prefix = os.path.basename(binary_path).replace(".exe", "").replace(".", "_")

    # 1. Decompile all functions
    print("[*] Decompiling all functions...")
    c_path = os.path.join(output_dir, prefix + "_decompiled.c")
    count = 0
    with open(c_path, "w") as f:
        f.write(f"// Ghidra decompiled output for: {program.getName()}\n")
        f.write("// Auto-generated by pyghidra\n\n")

        for func in func_manager.getFunctions(True):
            results = decomp.decompileFunction(func, 60, monitor)
            if results and results.decompileCompleted():
                c_code = results.getDecompiledFunction().getC()
                f.write(f"// Function: {func.getName()} @ 0x{func.getEntryPoint()}\n")
                f.write(c_code)
                f.write("\n\n")
            else:
                f.write(f"// FAILED to decompile: {func.getName()} @ 0x{func.getEntryPoint()}\n\n")
            count += 1
    print(f"[*] Decompiled {count} functions -> {c_path}")

    # 2. Function list with addresses and sizes
    print("[*] Exporting function list...")
    func_path = os.path.join(output_dir, prefix + "_functions.txt")
    with open(func_path, "w") as f:
        f.write(f"{'Name':<40s} {'Address':<12s} {'Size':<8s}\n")
        f.write("-" * 64 + "\n")
        for func in func_manager.getFunctions(True):
            body = func.getBody()
            size = body.getNumAddresses()
            f.write(f"{func.getName():<40s} 0x{func.getEntryPoint()!s:<10s} {size:<8d}\n")

    # 3. String table
    print("[*] Exporting strings...")
    str_path = os.path.join(output_dir, prefix + "_strings_ghidra.txt")
    with open(str_path, "w") as f:
        for data in listing.getDefinedData(True):
            dt = data.getDataType()
            if "string" in dt.getName().lower():
                val = data.getValue()
                if val:
                    f.write(f"0x{data.getAddress()!s:<10s} {val!s}\n")

    # 4. Import table
    print("[*] Exporting imports...")
    imp_path = os.path.join(output_dir, prefix + "_imports.txt")
    with open(imp_path, "w") as f:
        sym_table = program.getSymbolTable()
        for sym in sym_table.getExternalSymbols():
            f.write(f"{sym.getName():<40s} {sym.getParentNamespace()!s}\n")

    decomp.dispose()
    print(f"[*] Export complete. Files in: {output_dir}")
